//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod party_bulk;
pub mod party_address_bulk;
pub mod party_contact_bulk;
pub mod party_email_bulk;
pub mod party_phone_bulk;

pub use party_bulk::PartyBulkService;
pub use party_address_bulk::PartyAddressBulkService;
pub use party_contact_bulk::PartyContactBulkService;
pub use party_email_bulk::PartyEmailBulkService;
pub use party_phone_bulk::PartyPhoneBulkService;

// <<< CUSTOM
// END CUSTOM
