//! Bulk operations for PartyEmail entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreatePartyEmailDto;
use crate::application::service::PartyEmailService;
use crate::domain::entity::PartyEmail;

/// Bulk operation handler for PartyEmail entities.
///
/// Wraps `PartyEmailService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type PartyEmailBulkService = GenericBulkService<PartyEmail, CreatePartyEmailDto, PartyEmailService>;

// <<< CUSTOM
// END CUSTOM
