//! Bulk operations for PartyAddress entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreatePartyAddressDto;
use crate::application::service::PartyAddressService;
use crate::domain::entity::PartyAddress;

/// Bulk operation handler for PartyAddress entities.
///
/// Wraps `PartyAddressService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type PartyAddressBulkService = GenericBulkService<PartyAddress, CreatePartyAddressDto, PartyAddressService>;

// <<< CUSTOM
// END CUSTOM
