//! Bulk operations for PartyPhone entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreatePartyPhoneDto;
use crate::application::service::PartyPhoneService;
use crate::domain::entity::PartyPhone;

/// Bulk operation handler for PartyPhone entities.
///
/// Wraps `PartyPhoneService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type PartyPhoneBulkService = GenericBulkService<PartyPhone, CreatePartyPhoneDto, PartyPhoneService>;

// <<< CUSTOM
// END CUSTOM
