//! Bulk operations for PartyContact entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreatePartyContactDto;
use crate::application::service::PartyContactService;
use crate::domain::entity::PartyContact;

/// Bulk operation handler for PartyContact entities.
///
/// Wraps `PartyContactService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type PartyContactBulkService = GenericBulkService<PartyContact, CreatePartyContactDto, PartyContactService>;

// <<< CUSTOM
// END CUSTOM
