//! Bulk operations for Party entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreatePartyDto;
use crate::application::service::PartyService;
use crate::domain::entity::Party;

/// Bulk operation handler for Party entities.
///
/// Wraps `PartyService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type PartyBulkService = GenericBulkService<Party, CreatePartyDto, PartyService>;

// <<< CUSTOM
// END CUSTOM
