//! PartyPhone DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::PartyPhone;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new PartyPhone
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePartyPhoneDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "party_id")]
    pub party_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub label: String,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub phone: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_primary")]
    pub is_primary: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a PartyPhone
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePartyPhoneDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "party_id")]
    pub party_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub label: String,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub phone: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_primary")]
    pub is_primary: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a PartyPhone
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPartyPhoneDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_primary")]
    pub is_primary: Option<bool>,
}

impl PatchPartyPhoneDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.party_id.is_some() || self.company_id.is_some() || self.label.is_some() || self.phone.is_some() || self.is_primary.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for PartyPhone entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PartyPhoneResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub party_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub label: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub phone: String,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_primary: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for PartyPhone entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PartyPhoneListResponseDto {
    /// List of items
    pub items: Vec<PartyPhoneResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PartyPhoneListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PartyPhoneResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PartyPhoneSummaryDto {
    pub id: Uuid,
    pub party_id: Uuid,
    pub company_id: Uuid,
    pub label: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<PartyPhone> for PartyPhoneResponseDto {
    fn from(entity: PartyPhone) -> Self {
        Self {
            id: entity.id,
            party_id: entity.party_id,
            company_id: entity.company_id,
            label: entity.label,
            phone: entity.phone,
            is_primary: entity.is_primary,
            metadata: entity.metadata,
        }
    }
}

impl From<PartyPhone> for PartyPhoneSummaryDto {
    fn from(entity: PartyPhone) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            party_id: entity.party_id,
            company_id: entity.company_id,
            label: entity.label,
            created_at,
        }
    }
}

impl From<CreatePartyPhoneDto> for PartyPhone {
    fn from(dto: CreatePartyPhoneDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            party_id: dto.party_id,
            company_id: dto.company_id,
            label: dto.label,
            phone: dto.phone,
            is_primary: dto.is_primary,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&PartyPhone> for PartyPhoneResponseDto {
    fn from(entity: &PartyPhone) -> Self {
        Self {
            id: entity.id.clone(),
            party_id: entity.party_id.clone(),
            company_id: entity.company_id.clone(),
            label: entity.label.clone(),
            phone: entity.phone.clone(),
            is_primary: entity.is_primary.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePartyPhoneDto> for PartyPhone {
    fn from_create_dto(dto: CreatePartyPhoneDto) -> backbone_core::ServiceResult<Self> {
        Ok(PartyPhone::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePartyPhoneDto> for PartyPhone {
    fn apply_update(mut self, dto: UpdatePartyPhoneDto) -> backbone_core::ServiceResult<Self> {
        self.party_id = dto.party_id;
        self.company_id = dto.company_id;
        self.label = dto.label;
        self.phone = dto.phone;
        self.is_primary = dto.is_primary;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to PartyPhone here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
