//! Party DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Party;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::PartyKind;
use crate::domain::entity::PartyStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Party
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePartyDto {
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "party_code")]
    pub party_code: String,
    #[serde(alias = "party_kind")]
    pub party_kind: PartyKind,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "legal_name")]
    pub legal_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "first_name")]
    pub first_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_name")]
    pub last_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 25)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub npwp: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub nik: Option<String>,
    pub status: PartyStatus,
    #[cfg_attr(feature = "validation", validate(length(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Party
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePartyDto {
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "party_code")]
    pub party_code: String,
    #[serde(alias = "party_kind")]
    pub party_kind: PartyKind,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "legal_name")]
    pub legal_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "first_name")]
    pub first_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_name")]
    pub last_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 25)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub npwp: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub nik: Option<String>,
    pub status: PartyStatus,
    #[cfg_attr(feature = "validation", validate(length(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Party
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPartyDto {
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "party_code")]
    pub party_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "party_kind")]
    pub party_kind: Option<PartyKind>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 200)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "legal_name")]
    pub legal_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "first_name")]
    pub first_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "last_name")]
    pub last_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 25)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub npwp: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub nik: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<PartyStatus>,
    #[cfg_attr(feature = "validation", validate(length(max = 1000)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

impl PatchPartyDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.party_code.is_some() || self.party_kind.is_some() || self.name.is_some() || self.legal_name.is_some() || self.first_name.is_some() || self.last_name.is_some() || self.npwp.is_some() || self.nik.is_some() || self.status.is_some() || self.notes.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Party entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PartyResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub party_code: String,
    pub party_kind: PartyKind,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub legal_name: Option<String>,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub npwp: Option<String>,
    pub nik: Option<String>,
    pub status: PartyStatus,
    pub notes: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Party entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PartyListResponseDto {
    /// List of items
    pub items: Vec<PartyResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PartyListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PartyResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PartySummaryDto {
    pub id: Uuid,
    pub party_code: String,
    pub party_kind: PartyKind,
    pub name: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Party> for PartyResponseDto {
    fn from(entity: Party) -> Self {
        Self {
            id: entity.id,
            party_code: entity.party_code,
            party_kind: entity.party_kind,
            name: entity.name,
            legal_name: entity.legal_name,
            first_name: entity.first_name,
            last_name: entity.last_name,
            npwp: entity.npwp,
            nik: entity.nik,
            status: entity.status,
            notes: entity.notes,
            metadata: entity.metadata,
        }
    }
}

impl From<Party> for PartySummaryDto {
    fn from(entity: Party) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            party_code: entity.party_code,
            party_kind: entity.party_kind,
            name: entity.name,
            created_at,
        }
    }
}

impl From<CreatePartyDto> for Party {
    fn from(dto: CreatePartyDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            party_code: dto.party_code,
            party_kind: dto.party_kind,
            name: dto.name,
            legal_name: dto.legal_name,
            first_name: dto.first_name,
            last_name: dto.last_name,
            npwp: dto.npwp,
            nik: dto.nik,
            status: dto.status,
            notes: dto.notes,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Party> for PartyResponseDto {
    fn from(entity: &Party) -> Self {
        Self {
            id: entity.id.clone(),
            party_code: entity.party_code.clone(),
            party_kind: entity.party_kind.clone(),
            name: entity.name.clone(),
            legal_name: entity.legal_name.clone(),
            first_name: entity.first_name.clone(),
            last_name: entity.last_name.clone(),
            npwp: entity.npwp.clone(),
            nik: entity.nik.clone(),
            status: entity.status.clone(),
            notes: entity.notes.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePartyDto> for Party {
    fn from_create_dto(dto: CreatePartyDto) -> backbone_core::ServiceResult<Self> {
        Ok(Party::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePartyDto> for Party {
    fn apply_update(mut self, dto: UpdatePartyDto) -> backbone_core::ServiceResult<Self> {
        self.party_code = dto.party_code;
        self.party_kind = dto.party_kind;
        self.name = dto.name;
        self.legal_name = dto.legal_name;
        self.first_name = dto.first_name;
        self.last_name = dto.last_name;
        self.npwp = dto.npwp;
        self.nik = dto.nik;
        self.status = dto.status;
        self.notes = dto.notes;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Party here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
