//! PartyContact DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::PartyContact;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new PartyContact
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePartyContactDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "party_id")]
    pub party_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "job_title")]
    pub job_title: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub department: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_primary")]
    pub is_primary: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a PartyContact
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePartyContactDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "party_id")]
    pub party_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "job_title")]
    pub job_title: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub department: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_primary")]
    pub is_primary: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a PartyContact
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPartyContactDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "job_title")]
    pub job_title: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub department: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_primary")]
    pub is_primary: Option<bool>,
}

impl PatchPartyContactDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.party_id.is_some() || self.company_id.is_some() || self.name.is_some() || self.job_title.is_some() || self.department.is_some() || self.email.is_some() || self.phone.is_some() || self.is_primary.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for PartyContact entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PartyContactResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub party_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub job_title: Option<String>,
    pub department: Option<String>,
    pub email: Option<String>,
    pub phone: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_primary: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for PartyContact entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PartyContactListResponseDto {
    /// List of items
    pub items: Vec<PartyContactResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PartyContactListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PartyContactResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PartyContactSummaryDto {
    pub id: Uuid,
    pub party_id: Uuid,
    pub company_id: Uuid,
    pub name: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<PartyContact> for PartyContactResponseDto {
    fn from(entity: PartyContact) -> Self {
        Self {
            id: entity.id,
            party_id: entity.party_id,
            company_id: entity.company_id,
            name: entity.name,
            job_title: entity.job_title,
            department: entity.department,
            email: entity.email,
            phone: entity.phone,
            is_primary: entity.is_primary,
            metadata: entity.metadata,
        }
    }
}

impl From<PartyContact> for PartyContactSummaryDto {
    fn from(entity: PartyContact) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            party_id: entity.party_id,
            company_id: entity.company_id,
            name: entity.name,
            created_at,
        }
    }
}

impl From<CreatePartyContactDto> for PartyContact {
    fn from(dto: CreatePartyContactDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            party_id: dto.party_id,
            company_id: dto.company_id,
            name: dto.name,
            job_title: dto.job_title,
            department: dto.department,
            email: dto.email,
            phone: dto.phone,
            is_primary: dto.is_primary,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&PartyContact> for PartyContactResponseDto {
    fn from(entity: &PartyContact) -> Self {
        Self {
            id: entity.id.clone(),
            party_id: entity.party_id.clone(),
            company_id: entity.company_id.clone(),
            name: entity.name.clone(),
            job_title: entity.job_title.clone(),
            department: entity.department.clone(),
            email: entity.email.clone(),
            phone: entity.phone.clone(),
            is_primary: entity.is_primary.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePartyContactDto> for PartyContact {
    fn from_create_dto(dto: CreatePartyContactDto) -> backbone_core::ServiceResult<Self> {
        Ok(PartyContact::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePartyContactDto> for PartyContact {
    fn apply_update(mut self, dto: UpdatePartyContactDto) -> backbone_core::ServiceResult<Self> {
        self.party_id = dto.party_id;
        self.company_id = dto.company_id;
        self.name = dto.name;
        self.job_title = dto.job_title;
        self.department = dto.department;
        self.email = dto.email;
        self.phone = dto.phone;
        self.is_primary = dto.is_primary;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to PartyContact here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
