//! PartyAddress DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::PartyAddress;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::AddressType;
use crate::domain::entity::PartyStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new PartyAddress
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePartyAddressDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "party_id")]
    pub party_id: Uuid,
    #[serde(alias = "address_type")]
    pub address_type: AddressType,
    #[cfg_attr(feature = "validation", validate(length(max = 60)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub line1: String,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub line2: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "country_id")]
    pub country_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "province_id")]
    pub province_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "city_id")]
    pub city_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "district_id")]
    pub district_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "subdistrict_id")]
    pub subdistrict_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "postal_code")]
    pub postal_code: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub latitude: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub longitude: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_primary")]
    pub is_primary: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_billing")]
    pub is_billing: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_shipping")]
    pub is_shipping: bool,
    pub status: PartyStatus,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a PartyAddress
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePartyAddressDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "party_id")]
    pub party_id: Uuid,
    #[serde(alias = "address_type")]
    pub address_type: AddressType,
    #[cfg_attr(feature = "validation", validate(length(max = 60)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub line1: String,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub line2: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "country_id")]
    pub country_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "province_id")]
    pub province_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "city_id")]
    pub city_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "district_id")]
    pub district_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "subdistrict_id")]
    pub subdistrict_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "postal_code")]
    pub postal_code: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub latitude: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub longitude: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_primary")]
    pub is_primary: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_billing")]
    pub is_billing: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_shipping")]
    pub is_shipping: bool,
    pub status: PartyStatus,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a PartyAddress
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPartyAddressDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "address_type")]
    pub address_type: Option<AddressType>,
    #[cfg_attr(feature = "validation", validate(length(max = 60)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub line1: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub line2: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "country_id")]
    pub country_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "province_id")]
    pub province_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "city_id")]
    pub city_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "district_id")]
    pub district_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "subdistrict_id")]
    pub subdistrict_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "postal_code")]
    pub postal_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub latitude: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub longitude: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_primary")]
    pub is_primary: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_billing")]
    pub is_billing: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_shipping")]
    pub is_shipping: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<PartyStatus>,
}

impl PatchPartyAddressDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.party_id.is_some() || self.address_type.is_some() || self.label.is_some() || self.line1.is_some() || self.line2.is_some() || self.country_id.is_some() || self.province_id.is_some() || self.city_id.is_some() || self.district_id.is_some() || self.subdistrict_id.is_some() || self.postal_code.is_some() || self.latitude.is_some() || self.longitude.is_some() || self.is_primary.is_some() || self.is_billing.is_some() || self.is_shipping.is_some() || self.status.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for PartyAddress entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PartyAddressResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub party_id: Uuid,
    pub address_type: AddressType,
    pub label: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub line1: String,
    pub line2: Option<String>,
    pub country_id: Option<Uuid>,
    pub province_id: Option<Uuid>,
    pub city_id: Option<Uuid>,
    pub district_id: Option<Uuid>,
    pub subdistrict_id: Option<Uuid>,
    pub postal_code: Option<String>,
    pub latitude: Option<Decimal>,
    pub longitude: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_primary: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_billing: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_shipping: bool,
    pub status: PartyStatus,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for PartyAddress entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PartyAddressListResponseDto {
    /// List of items
    pub items: Vec<PartyAddressResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PartyAddressListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PartyAddressResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PartyAddressSummaryDto {
    pub id: Uuid,
    pub party_id: Uuid,
    pub address_type: AddressType,
    pub label: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<PartyAddress> for PartyAddressResponseDto {
    fn from(entity: PartyAddress) -> Self {
        Self {
            id: entity.id,
            party_id: entity.party_id,
            address_type: entity.address_type,
            label: entity.label,
            line1: entity.line1,
            line2: entity.line2,
            country_id: entity.country_id,
            province_id: entity.province_id,
            city_id: entity.city_id,
            district_id: entity.district_id,
            subdistrict_id: entity.subdistrict_id,
            postal_code: entity.postal_code,
            latitude: entity.latitude,
            longitude: entity.longitude,
            is_primary: entity.is_primary,
            is_billing: entity.is_billing,
            is_shipping: entity.is_shipping,
            status: entity.status,
            metadata: entity.metadata,
        }
    }
}

impl From<PartyAddress> for PartyAddressSummaryDto {
    fn from(entity: PartyAddress) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            party_id: entity.party_id,
            address_type: entity.address_type,
            label: entity.label,
            created_at,
        }
    }
}

impl From<CreatePartyAddressDto> for PartyAddress {
    fn from(dto: CreatePartyAddressDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            party_id: dto.party_id,
            address_type: dto.address_type,
            label: dto.label,
            line1: dto.line1,
            line2: dto.line2,
            country_id: dto.country_id,
            province_id: dto.province_id,
            city_id: dto.city_id,
            district_id: dto.district_id,
            subdistrict_id: dto.subdistrict_id,
            postal_code: dto.postal_code,
            latitude: dto.latitude,
            longitude: dto.longitude,
            is_primary: dto.is_primary,
            is_billing: dto.is_billing,
            is_shipping: dto.is_shipping,
            status: dto.status,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&PartyAddress> for PartyAddressResponseDto {
    fn from(entity: &PartyAddress) -> Self {
        Self {
            id: entity.id.clone(),
            party_id: entity.party_id.clone(),
            address_type: entity.address_type.clone(),
            label: entity.label.clone(),
            line1: entity.line1.clone(),
            line2: entity.line2.clone(),
            country_id: entity.country_id.clone(),
            province_id: entity.province_id.clone(),
            city_id: entity.city_id.clone(),
            district_id: entity.district_id.clone(),
            subdistrict_id: entity.subdistrict_id.clone(),
            postal_code: entity.postal_code.clone(),
            latitude: entity.latitude.clone(),
            longitude: entity.longitude.clone(),
            is_primary: entity.is_primary.clone(),
            is_billing: entity.is_billing.clone(),
            is_shipping: entity.is_shipping.clone(),
            status: entity.status.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePartyAddressDto> for PartyAddress {
    fn from_create_dto(dto: CreatePartyAddressDto) -> backbone_core::ServiceResult<Self> {
        Ok(PartyAddress::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePartyAddressDto> for PartyAddress {
    fn apply_update(mut self, dto: UpdatePartyAddressDto) -> backbone_core::ServiceResult<Self> {
        self.party_id = dto.party_id;
        self.address_type = dto.address_type;
        self.label = dto.label;
        self.line1 = dto.line1;
        self.line2 = dto.line2;
        self.country_id = dto.country_id;
        self.province_id = dto.province_id;
        self.city_id = dto.city_id;
        self.district_id = dto.district_id;
        self.subdistrict_id = dto.subdistrict_id;
        self.postal_code = dto.postal_code;
        self.latitude = dto.latitude;
        self.longitude = dto.longitude;
        self.is_primary = dto.is_primary;
        self.is_billing = dto.is_billing;
        self.is_shipping = dto.is_shipping;
        self.status = dto.status;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to PartyAddress here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
