//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod party_specification;
pub mod party_address_specification;
pub mod party_contact_specification;
pub mod party_email_specification;
pub mod party_phone_specification;

// <<< CUSTOM
// END CUSTOM
