//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod party_domain_policy;
pub mod party_address_domain_policy;
pub mod party_contact_domain_policy;
pub mod party_email_domain_policy;
pub mod party_phone_domain_policy;

pub use party_domain_policy::PartyDomainPolicy;
pub use party_address_domain_policy::PartyAddressDomainPolicy;
pub use party_contact_domain_policy::PartyContactDomainPolicy;
pub use party_email_domain_policy::PartyEmailDomainPolicy;
pub use party_phone_domain_policy::PartyPhoneDomainPolicy;

// <<< CUSTOM
// END CUSTOM
