//! Domain policy for Party aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::Party;

/// Domain policy for Party — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<Party>` in the `// <<< CUSTOM` zone.
pub type PartyDomainPolicy = PermitAllPolicy<Party>;

// <<< CUSTOM
// END CUSTOM
