//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod party_service;
pub mod party_address_service;
pub mod party_contact_service;
pub mod party_email_service;
pub mod party_phone_service;

// <<< CUSTOM
pub mod party_write_service;
// END CUSTOM

pub use party_service::PartyService;
pub use party_address_service::PartyAddressService;
pub use party_contact_service::PartyContactService;
pub use party_email_service::PartyEmailService;
pub use party_phone_service::PartyPhoneService;
// <<< CUSTOM
pub use party_write_service::{
    validate_nik, validate_npwp, NewAddress, NewContact, NewEmail, NewParty, NewPhone,
    PartyWriteError, PartyWriteService,
};
// END CUSTOM