//! Application service for PartyAddress entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `party_address_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreatePartyAddressDto, UpdatePartyAddressDto};
use crate::domain::entity::PartyAddress;
use crate::infrastructure::persistence::PartyAddressRepository;

/// Application service for PartyAddress entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `party_address_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PartyAddressServiceCustom {
///     inner: Arc<PartyAddressService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PartyAddressService = GenericCrudService<
    PartyAddress,
    CreatePartyAddressDto,
    UpdatePartyAddressDto,
    PartyAddressRepository,
>;

// <<< CUSTOM
// END CUSTOM
