//! Application service for Party entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `party_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreatePartyDto, UpdatePartyDto};
use crate::domain::entity::Party;
use crate::infrastructure::persistence::PartyRepository;

/// Application service for Party entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `party_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PartyServiceCustom {
///     inner: Arc<PartyService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PartyService = GenericCrudService<
    Party,
    CreatePartyDto,
    UpdatePartyDto,
    PartyRepository,
>;

// <<< CUSTOM
// END CUSTOM
