//! Application service for PartyPhone entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `party_phone_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreatePartyPhoneDto, UpdatePartyPhoneDto};
use crate::domain::entity::PartyPhone;
use crate::infrastructure::persistence::PartyPhoneRepository;

/// Application service for PartyPhone entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `party_phone_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PartyPhoneServiceCustom {
///     inner: Arc<PartyPhoneService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PartyPhoneService = GenericCrudService<
    PartyPhone,
    CreatePartyPhoneDto,
    UpdatePartyPhoneDto,
    PartyPhoneRepository,
>;

// <<< CUSTOM
// END CUSTOM
