//! Application service for PartyEmail entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `party_email_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreatePartyEmailDto, UpdatePartyEmailDto};
use crate::domain::entity::PartyEmail;
use crate::infrastructure::persistence::PartyEmailRepository;

/// Application service for PartyEmail entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `party_email_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PartyEmailServiceCustom {
///     inner: Arc<PartyEmailService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PartyEmailService = GenericCrudService<
    PartyEmail,
    CreatePartyEmailDto,
    UpdatePartyEmailDto,
    PartyEmailRepository,
>;

// <<< CUSTOM
// END CUSTOM
