-- PartyPhone Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the party.party_phones table.
-- Customize this file to add your initial data.

-- INSERT INTO party.party_phones (
--     id,
--     party_id,
--     label,
--     phone,
--     is_primary,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO party.party_phones (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

