-- PartyAddress Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the party.party_addresses table.
-- Customize this file to add your initial data.

-- INSERT INTO party.party_addresses (
--     id,
--     party_id,
--     address_type,
--     label,
--     line1,
--     line2,
--     country_id,
--     province_id,
--     city_id,
--     district_id,
--     subdistrict_id,
--     postal_code,
--     latitude,
--     longitude,
--     is_primary,
--     is_billing,
--     is_shipping,
--     status,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO party.party_addresses (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

