-- Enum types for party module
-- Generated by metaphor-schema

-- Create party_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'party_kind') THEN
        CREATE TYPE party_kind AS ENUM ('organization', 'person');
    END IF;
END
$$;

-- Create party_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'party_status') THEN
        CREATE TYPE party_status AS ENUM ('active', 'inactive', 'blocked');
    END IF;
END
$$;

-- Create address_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'address_type') THEN
        CREATE TYPE address_type AS ENUM ('billing', 'shipping', 'office', 'home', 'warehouse', 'other');
    END IF;
END
$$;

