-- Audit Triggers Migration for party module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: Party (party.parties)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION party.parties_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS parties_insert_audit ON party.parties;
CREATE TRIGGER parties_insert_audit BEFORE INSERT ON party.parties
    FOR EACH ROW EXECUTE FUNCTION party.parties_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS parties_update_audit ON party.parties;
CREATE TRIGGER parties_update_audit BEFORE UPDATE ON party.parties
    FOR EACH ROW EXECUTE FUNCTION party.parties_audit_timestamp();

-- ==============================================================================
-- Table: PartyAddress (party.party_addresses)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION party.party_addresses_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS party_addresses_insert_audit ON party.party_addresses;
CREATE TRIGGER party_addresses_insert_audit BEFORE INSERT ON party.party_addresses
    FOR EACH ROW EXECUTE FUNCTION party.party_addresses_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS party_addresses_update_audit ON party.party_addresses;
CREATE TRIGGER party_addresses_update_audit BEFORE UPDATE ON party.party_addresses
    FOR EACH ROW EXECUTE FUNCTION party.party_addresses_audit_timestamp();

-- ==============================================================================
-- Table: PartyContact (party.party_contacts)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION party.party_contacts_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS party_contacts_insert_audit ON party.party_contacts;
CREATE TRIGGER party_contacts_insert_audit BEFORE INSERT ON party.party_contacts
    FOR EACH ROW EXECUTE FUNCTION party.party_contacts_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS party_contacts_update_audit ON party.party_contacts;
CREATE TRIGGER party_contacts_update_audit BEFORE UPDATE ON party.party_contacts
    FOR EACH ROW EXECUTE FUNCTION party.party_contacts_audit_timestamp();

-- ==============================================================================
-- Table: PartyEmail (party.party_emails)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION party.party_emails_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS party_emails_insert_audit ON party.party_emails;
CREATE TRIGGER party_emails_insert_audit BEFORE INSERT ON party.party_emails
    FOR EACH ROW EXECUTE FUNCTION party.party_emails_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS party_emails_update_audit ON party.party_emails;
CREATE TRIGGER party_emails_update_audit BEFORE UPDATE ON party.party_emails
    FOR EACH ROW EXECUTE FUNCTION party.party_emails_audit_timestamp();

-- ==============================================================================
-- Table: PartyPhone (party.party_phones)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION party.party_phones_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS party_phones_insert_audit ON party.party_phones;
CREATE TRIGGER party_phones_insert_audit BEFORE INSERT ON party.party_phones
    FOR EACH ROW EXECUTE FUNCTION party.party_phones_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS party_phones_update_audit ON party.party_phones;
CREATE TRIGGER party_phones_update_audit BEFORE UPDATE ON party.party_phones
    FOR EACH ROW EXECUTE FUNCTION party.party_phones_audit_timestamp();

