-- Migration: Create party_phones table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS party;

CREATE TABLE IF NOT EXISTS party.party_phones (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    party_id UUID NOT NULL,
    label TEXT NOT NULL DEFAULT 'mobile',
    phone TEXT NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_party_phones_party_id_is_primary ON party.party_phones (party_id, is_primary);

CREATE UNIQUE INDEX IF NOT EXISTS idx_party_phones_party_id ON party.party_phones (party_id) WHERE is_primary AND (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_party_phones_metadata_gin ON party.party_phones USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_party_phones_metadata_deleted_at ON party.party_phones ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_party_phones_metadata_created_at ON party.party_phones ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_party_phones_metadata_updated_at ON party.party_phones ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION party.party_phones_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS party_phones_insert_audit ON party.party_phones;
CREATE TRIGGER party_phones_insert_audit BEFORE INSERT ON party.party_phones
    FOR EACH ROW EXECUTE FUNCTION party.party_phones_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS party_phones_update_audit ON party.party_phones;
CREATE TRIGGER party_phones_update_audit BEFORE UPDATE ON party.party_phones
    FOR EACH ROW EXECUTE FUNCTION party.party_phones_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE party.party_phones ADD CONSTRAINT fk_party_phones_party_id FOREIGN KEY (party_id) REFERENCES party.parties (id);
