-- Migration: Create party_addresses table
-- Generated by metaphor-schema

-- Create address_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'address_type') THEN
        CREATE TYPE address_type AS ENUM ('billing', 'shipping', 'office', 'home', 'warehouse', 'other');
    END IF;
END
$$;

-- Create party_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'party_status') THEN
        CREATE TYPE party_status AS ENUM ('active', 'inactive', 'blocked');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS party;

CREATE TABLE IF NOT EXISTS party.party_addresses (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    party_id UUID NOT NULL,
    address_type address_type NOT NULL DEFAULT 'home',
    label TEXT,
    line1 TEXT NOT NULL,
    line2 TEXT,
    country_id UUID,
    province_id UUID,
    city_id UUID,
    district_id UUID,
    subdistrict_id UUID,
    postal_code TEXT,
    latitude NUMERIC,
    longitude NUMERIC,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    is_billing BOOLEAN NOT NULL DEFAULT FALSE,
    is_shipping BOOLEAN NOT NULL DEFAULT FALSE,
    status party_status NOT NULL DEFAULT 'active',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_party_addresses_party_id_is_primary ON party.party_addresses (party_id, is_primary);

CREATE UNIQUE INDEX IF NOT EXISTS idx_party_addresses_party_id ON party.party_addresses (party_id) WHERE is_primary AND (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_party_addresses_party_id_address_type ON party.party_addresses (party_id, address_type);

CREATE INDEX IF NOT EXISTS idx_party_addresses_subdistrict_id ON party.party_addresses (subdistrict_id);

CREATE INDEX IF NOT EXISTS idx_party_addresses_postal_code ON party.party_addresses (postal_code);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_party_addresses_metadata_gin ON party.party_addresses USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_party_addresses_metadata_deleted_at ON party.party_addresses ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_party_addresses_metadata_created_at ON party.party_addresses ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_party_addresses_metadata_updated_at ON party.party_addresses ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION party.party_addresses_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS party_addresses_insert_audit ON party.party_addresses;
CREATE TRIGGER party_addresses_insert_audit BEFORE INSERT ON party.party_addresses
    FOR EACH ROW EXECUTE FUNCTION party.party_addresses_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS party_addresses_update_audit ON party.party_addresses;
CREATE TRIGGER party_addresses_update_audit BEFORE UPDATE ON party.party_addresses
    FOR EACH ROW EXECUTE FUNCTION party.party_addresses_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE party.party_addresses ADD CONSTRAINT fk_party_addresses_party_id FOREIGN KEY (party_id) REFERENCES party.parties (id);
