-- Company RLS fence for party module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for party.parties
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE party.parties ENABLE ROW LEVEL SECURITY;
ALTER TABLE party.parties FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS parties_company_isolation ON party.parties;
CREATE POLICY parties_company_isolation ON party.parties
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid OR company_id IS NULL)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid OR company_id IS NULL);

-- Migration: company row-level-security fence for party.party_addresses
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE party.party_addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE party.party_addresses FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS party_addresses_company_isolation ON party.party_addresses;
CREATE POLICY party_addresses_company_isolation ON party.party_addresses
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid OR company_id IS NULL)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid OR company_id IS NULL);

-- Migration: company row-level-security fence for party.party_contacts
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE party.party_contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE party.party_contacts FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS party_contacts_company_isolation ON party.party_contacts;
CREATE POLICY party_contacts_company_isolation ON party.party_contacts
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid OR company_id IS NULL)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid OR company_id IS NULL);

-- Migration: company row-level-security fence for party.party_emails
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE party.party_emails ENABLE ROW LEVEL SECURITY;
ALTER TABLE party.party_emails FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS party_emails_company_isolation ON party.party_emails;
CREATE POLICY party_emails_company_isolation ON party.party_emails
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid OR company_id IS NULL)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid OR company_id IS NULL);

-- Migration: company row-level-security fence for party.party_phones
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE party.party_phones ENABLE ROW LEVEL SECURITY;
ALTER TABLE party.party_phones FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS party_phones_company_isolation ON party.party_phones;
CREATE POLICY party_phones_company_isolation ON party.party_phones
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid OR company_id IS NULL)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid OR company_id IS NULL);

