-- Migration: Create parties table
-- Generated by metaphor-schema

-- Create party_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'party_kind') THEN
        CREATE TYPE party_kind AS ENUM ('organization', 'person');
    END IF;
END
$$;

-- Create party_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'party_status') THEN
        CREATE TYPE party_status AS ENUM ('active', 'inactive', 'blocked');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS party;

CREATE TABLE IF NOT EXISTS party.parties (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    party_code TEXT NOT NULL,
    party_kind party_kind NOT NULL DEFAULT 'organization',
    name TEXT NOT NULL,
    legal_name TEXT,
    first_name TEXT,
    last_name TEXT,
    npwp TEXT,
    nik TEXT,
    status party_status NOT NULL DEFAULT 'active',
    notes TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_parties_party_code ON party.parties (party_code) WHERE (metadata->>'deleted_at') IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_parties_npwp ON party.parties (npwp) WHERE npwp IS NOT NULL AND (metadata->>'deleted_at') IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_parties_nik ON party.parties (nik) WHERE nik IS NOT NULL AND (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_parties_party_kind_status ON party.parties (party_kind, status);

CREATE INDEX IF NOT EXISTS idx_parties_name ON party.parties (name);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_parties_metadata_gin ON party.parties USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_parties_metadata_deleted_at ON party.parties ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_parties_metadata_created_at ON party.parties ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_parties_metadata_updated_at ON party.parties ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION party.parties_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS parties_insert_audit ON party.parties;
CREATE TRIGGER parties_insert_audit BEFORE INSERT ON party.parties
    FOR EACH ROW EXECUTE FUNCTION party.parties_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS parties_update_audit ON party.parties;
CREATE TRIGGER parties_update_audit BEFORE UPDATE ON party.parties
    FOR EACH ROW EXECUTE FUNCTION party.parties_audit_timestamp();
