//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod party_events;
pub mod party_event_handlers;
pub mod party_address_events;
pub mod party_address_event_handlers;
pub mod party_contact_events;
pub mod party_contact_event_handlers;
pub mod party_email_events;
pub mod party_email_event_handlers;
pub mod party_phone_events;
pub mod party_phone_event_handlers;

pub use party_events::{PartyEvent, PartyEventPublisher, NoopPartyEventPublisher};
pub use party_event_handlers::PartyEventHandler;
pub use party_address_events::{PartyAddressEvent, PartyAddressEventPublisher, NoopPartyAddressEventPublisher};
pub use party_address_event_handlers::PartyAddressEventHandler;
pub use party_contact_events::{PartyContactEvent, PartyContactEventPublisher, NoopPartyContactEventPublisher};
pub use party_contact_event_handlers::PartyContactEventHandler;
pub use party_email_events::{PartyEmailEvent, PartyEmailEventPublisher, NoopPartyEmailEventPublisher};
pub use party_email_event_handlers::PartyEmailEventHandler;
pub use party_phone_events::{PartyPhoneEvent, PartyPhoneEventPublisher, NoopPartyPhoneEventPublisher};
pub use party_phone_event_handlers::PartyPhoneEventHandler;

// <<< CUSTOM
// END CUSTOM
