//! Domain events for PartyContact entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PartyContact;

/// Domain events for PartyContact — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PartyContact>)` variant.
pub type PartyContactEvent = CrudEvent<PartyContact>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PartyContact events.
pub type PartyContactEventPublisher = Arc<dyn CrudEventPublisher<PartyContact> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPartyContactEventPublisher = NoOpCrudEventPublisher<PartyContact>;
