//! Domain events for Party entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Party;

/// Domain events for Party — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Party>)` variant.
pub type PartyEvent = CrudEvent<Party>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Party events.
pub type PartyEventPublisher = Arc<dyn CrudEventPublisher<Party> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPartyEventPublisher = NoOpCrudEventPublisher<Party>;
