//! Domain events for PartyEmail entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PartyEmail;

/// Domain events for PartyEmail — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PartyEmail>)` variant.
pub type PartyEmailEvent = CrudEvent<PartyEmail>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PartyEmail events.
pub type PartyEmailEventPublisher = Arc<dyn CrudEventPublisher<PartyEmail> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPartyEmailEventPublisher = NoOpCrudEventPublisher<PartyEmail>;
