//! Event handler trait for PartyAddress events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PartyAddressEvent;

/// Event handler for PartyAddress events.
/// Implement this trait to react to PartyAddress lifecycle events.
pub trait PartyAddressEventHandler: EventHandler<PartyAddressEvent> {}
