//! Event handler trait for PartyPhone events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PartyPhoneEvent;

/// Event handler for PartyPhone events.
/// Implement this trait to react to PartyPhone lifecycle events.
pub trait PartyPhoneEventHandler: EventHandler<PartyPhoneEvent> {}
