//! Event handler trait for PartyContact events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PartyContactEvent;

/// Event handler for PartyContact events.
/// Implement this trait to react to PartyContact lifecycle events.
pub trait PartyContactEventHandler: EventHandler<PartyContactEvent> {}
