//! Domain events for PartyAddress entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PartyAddress;

/// Domain events for PartyAddress — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PartyAddress>)` variant.
pub type PartyAddressEvent = CrudEvent<PartyAddress>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PartyAddress events.
pub type PartyAddressEventPublisher = Arc<dyn CrudEventPublisher<PartyAddress> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPartyAddressEventPublisher = NoOpCrudEventPublisher<PartyAddress>;
