//! Domain events for PartyPhone entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PartyPhone;

/// Domain events for PartyPhone — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PartyPhone>)` variant.
pub type PartyPhoneEvent = CrudEvent<PartyPhone>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PartyPhone events.
pub type PartyPhoneEventPublisher = Arc<dyn CrudEventPublisher<PartyPhone> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPartyPhoneEventPublisher = NoOpCrudEventPublisher<PartyPhone>;
