//! Event handler trait for Party events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PartyEvent;

/// Event handler for Party events.
/// Implement this trait to react to Party lifecycle events.
pub trait PartyEventHandler: EventHandler<PartyEvent> {}
