//! Event handler trait for PartyEmail events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PartyEmailEvent;

/// Event handler for PartyEmail events.
/// Implement this trait to react to PartyEmail lifecycle events.
pub trait PartyEmailEventHandler: EventHandler<PartyEmailEvent> {}
