//! Event subscriber type aliases for Party module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::PartyEvent;
use crate::domain::event::PartyAddressEvent;
use crate::domain::event::PartyContactEvent;
use crate::domain::event::PartyEmailEvent;
use crate::domain::event::PartyPhoneEvent;

/// Subscriber for Party events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type PartyEventSubscriber = GenericEventSubscriber<PartyEvent>;

/// Subscriber for PartyAddress events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type PartyAddressEventSubscriber = GenericEventSubscriber<PartyAddressEvent>;

/// Subscriber for PartyContact events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type PartyContactEventSubscriber = GenericEventSubscriber<PartyContactEvent>;

/// Subscriber for PartyEmail events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type PartyEmailEventSubscriber = GenericEventSubscriber<PartyEmailEvent>;

/// Subscriber for PartyPhone events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type PartyPhoneEventSubscriber = GenericEventSubscriber<PartyPhoneEvent>;

// <<< CUSTOM
// END CUSTOM
