//! PartyAddress seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial PartyAddress data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// PARTYADDRESS SEEDER
// ============================================================================

/// Seeder for party_address
pub struct SeedPartyAddressSeeder;

impl SeedPartyAddressSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedPartyAddressSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedPartyAddressSeeder {
    fn name(&self) -> &'static str {
        "SeedPartyAddressSeeder"
    }

    fn order(&self) -> i32 {
        2
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if party.party_addresses table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM party.party_addresses")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/party_address_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM party.party_addresses")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

