//! PartyPhone seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial PartyPhone data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// PARTYPHONE SEEDER
// ============================================================================

/// Seeder for party_phone
pub struct SeedPartyPhoneSeeder;

impl SeedPartyPhoneSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedPartyPhoneSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedPartyPhoneSeeder {
    fn name(&self) -> &'static str {
        "SeedPartyPhoneSeeder"
    }

    fn order(&self) -> i32 {
        5
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if party.party_phones table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM party.party_phones")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/party_phone_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM party.party_phones")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

