//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod party_repository;
pub mod party_address_repository;
pub mod party_contact_repository;
pub mod party_email_repository;
pub mod party_phone_repository;

// Re-exports
pub use party_repository::{
    PartyRepository,
    PartyPaginationParams,
    PartyPaginatedResult,
    PartyFilter,
};
pub use party_address_repository::{
    PartyAddressRepository,
    PartyAddressPaginationParams,
    PartyAddressPaginatedResult,
    PartyAddressFilter,
};
pub use party_contact_repository::{
    PartyContactRepository,
    PartyContactPaginationParams,
    PartyContactPaginatedResult,
    PartyContactFilter,
};
pub use party_email_repository::{
    PartyEmailRepository,
    PartyEmailPaginationParams,
    PartyEmailPaginatedResult,
    PartyEmailFilter,
};
pub use party_phone_repository::{
    PartyPhoneRepository,
    PartyPhonePaginationParams,
    PartyPhonePaginatedResult,
    PartyPhoneFilter,
};
