//! Repository trait for PartyContact aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PartyContact aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::PartyContact;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PartyContactPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PartyContactPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PartyContactPaginatedResult {
    pub data: Vec<PartyContact>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PartyContactFilter {
    pub party_id: Option<Uuid>,
    pub name: Option<String>,
    pub job_title: Option<String>,
    pub department: Option<String>,
    pub email: Option<String>,
    pub phone: Option<String>,
    pub is_primary: Option<bool>,
}

impl PartyContactFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.party_id.is_some() || self.name.is_some() || self.job_title.is_some() || self.department.is_some() || self.email.is_some() || self.phone.is_some() || self.is_primary.is_some()
    }
}

/// Repository trait for PartyContact aggregate
///
/// This trait defines the persistence contract for PartyContact entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PartyContactRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new party_contact entity
    async fn save(&self, entity: &PartyContact) -> Result<PartyContact>;

    /// Find party_contact by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PartyContact>>;

    /// Find all party_contact entities
    async fn find_all(&self) -> Result<Vec<PartyContact>>;

    /// Update party_contact by ID
    async fn update(&self, id: &str, entity: &PartyContact) -> Result<Option<PartyContact>>;

    /// Delete party_contact by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List party_contact with pagination
    async fn list(&self, params: PartyContactPaginationParams) -> Result<PartyContactPaginatedResult>;

    /// List party_contact with pagination and filters
    async fn list_with_filters(&self, params: PartyContactPaginationParams, filters: PartyContactFilter) -> Result<PartyContactPaginatedResult>;

    /// Count all party_contact entities
    async fn count(&self) -> Result<u64>;

    /// Count party_contact entities matching filters
    async fn count_with_filters(&self, filters: PartyContactFilter) -> Result<u64>;

    /// Check if party_contact exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete party_contact by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted party_contact by ID
    async fn restore(&self, id: &str) -> Result<Option<PartyContact>>;

    /// List soft-deleted party_contact entities
    async fn list_deleted(&self, params: PartyContactPaginationParams) -> Result<PartyContactPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save party_contact entities
    async fn bulk_save(&self, entities: &[PartyContact]) -> Result<Vec<PartyContact>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
