//! Repository trait for PartyEmail aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PartyEmail aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::PartyEmail;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PartyEmailPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PartyEmailPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PartyEmailPaginatedResult {
    pub data: Vec<PartyEmail>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PartyEmailFilter {
    pub party_id: Option<Uuid>,
    pub company_id: Option<Uuid>,
    pub label: Option<String>,
    pub email: Option<String>,
    pub is_primary: Option<bool>,
}

impl PartyEmailFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.party_id.is_some() || self.company_id.is_some() || self.label.is_some() || self.email.is_some() || self.is_primary.is_some()
    }
}

/// Repository trait for PartyEmail aggregate
///
/// This trait defines the persistence contract for PartyEmail entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PartyEmailRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new party_email entity
    async fn save(&self, entity: &PartyEmail) -> Result<PartyEmail>;

    /// Find party_email by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PartyEmail>>;

    /// Find all party_email entities
    async fn find_all(&self) -> Result<Vec<PartyEmail>>;

    /// Update party_email by ID
    async fn update(&self, id: &str, entity: &PartyEmail) -> Result<Option<PartyEmail>>;

    /// Delete party_email by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List party_email with pagination
    async fn list(&self, params: PartyEmailPaginationParams) -> Result<PartyEmailPaginatedResult>;

    /// List party_email with pagination and filters
    async fn list_with_filters(&self, params: PartyEmailPaginationParams, filters: PartyEmailFilter) -> Result<PartyEmailPaginatedResult>;

    /// Count all party_email entities
    async fn count(&self) -> Result<u64>;

    /// Count party_email entities matching filters
    async fn count_with_filters(&self, filters: PartyEmailFilter) -> Result<u64>;

    /// Check if party_email exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete party_email by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted party_email by ID
    async fn restore(&self, id: &str) -> Result<Option<PartyEmail>>;

    /// List soft-deleted party_email entities
    async fn list_deleted(&self, params: PartyEmailPaginationParams) -> Result<PartyEmailPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save party_email entities
    async fn bulk_save(&self, entities: &[PartyEmail]) -> Result<Vec<PartyEmail>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
