//! Repository trait for PartyPhone aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PartyPhone aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::PartyPhone;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PartyPhonePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PartyPhonePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PartyPhonePaginatedResult {
    pub data: Vec<PartyPhone>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PartyPhoneFilter {
    pub party_id: Option<Uuid>,
    pub company_id: Option<Uuid>,
    pub label: Option<String>,
    pub phone: Option<String>,
    pub is_primary: Option<bool>,
}

impl PartyPhoneFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.party_id.is_some() || self.company_id.is_some() || self.label.is_some() || self.phone.is_some() || self.is_primary.is_some()
    }
}

/// Repository trait for PartyPhone aggregate
///
/// This trait defines the persistence contract for PartyPhone entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PartyPhoneRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new party_phone entity
    async fn save(&self, entity: &PartyPhone) -> Result<PartyPhone>;

    /// Find party_phone by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PartyPhone>>;

    /// Find all party_phone entities
    async fn find_all(&self) -> Result<Vec<PartyPhone>>;

    /// Update party_phone by ID
    async fn update(&self, id: &str, entity: &PartyPhone) -> Result<Option<PartyPhone>>;

    /// Delete party_phone by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List party_phone with pagination
    async fn list(&self, params: PartyPhonePaginationParams) -> Result<PartyPhonePaginatedResult>;

    /// List party_phone with pagination and filters
    async fn list_with_filters(&self, params: PartyPhonePaginationParams, filters: PartyPhoneFilter) -> Result<PartyPhonePaginatedResult>;

    /// Count all party_phone entities
    async fn count(&self) -> Result<u64>;

    /// Count party_phone entities matching filters
    async fn count_with_filters(&self, filters: PartyPhoneFilter) -> Result<u64>;

    /// Check if party_phone exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete party_phone by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted party_phone by ID
    async fn restore(&self, id: &str) -> Result<Option<PartyPhone>>;

    /// List soft-deleted party_phone entities
    async fn list_deleted(&self, params: PartyPhonePaginationParams) -> Result<PartyPhonePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save party_phone entities
    async fn bulk_save(&self, entities: &[PartyPhone]) -> Result<Vec<PartyPhone>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
