//! Repository trait for Party aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Party aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;

use crate::domain::entity::{Party, PartyKind, PartyStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PartyPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PartyPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PartyPaginatedResult {
    pub data: Vec<Party>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PartyFilter {
    pub party_code: Option<String>,
    pub party_kind: Option<PartyKind>,
    pub name: Option<String>,
    pub legal_name: Option<String>,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub npwp: Option<String>,
    pub nik: Option<String>,
    pub status: Option<PartyStatus>,
    pub notes: Option<String>,
}

impl PartyFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.party_code.is_some() || self.party_kind.is_some() || self.name.is_some() || self.legal_name.is_some() || self.first_name.is_some() || self.last_name.is_some() || self.npwp.is_some() || self.nik.is_some() || self.status.is_some() || self.notes.is_some()
    }
}

/// Repository trait for Party aggregate
///
/// This trait defines the persistence contract for Party entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PartyRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new party entity
    async fn save(&self, entity: &Party) -> Result<Party>;

    /// Find party by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Party>>;

    /// Find all party entities
    async fn find_all(&self) -> Result<Vec<Party>>;

    /// Update party by ID
    async fn update(&self, id: &str, entity: &Party) -> Result<Option<Party>>;

    /// Delete party by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List party with pagination
    async fn list(&self, params: PartyPaginationParams) -> Result<PartyPaginatedResult>;

    /// List party with pagination and filters
    async fn list_with_filters(&self, params: PartyPaginationParams, filters: PartyFilter) -> Result<PartyPaginatedResult>;

    /// Count all party entities
    async fn count(&self) -> Result<u64>;

    /// Count party entities matching filters
    async fn count_with_filters(&self, filters: PartyFilter) -> Result<u64>;

    /// Check if party exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete party by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted party by ID
    async fn restore(&self, id: &str) -> Result<Option<Party>>;

    /// List soft-deleted party entities
    async fn list_deleted(&self, params: PartyPaginationParams) -> Result<PartyPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save party entities
    async fn bulk_save(&self, entities: &[Party]) -> Result<Vec<Party>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
