//! Repository trait for PartyAddress aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PartyAddress aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{PartyAddress, AddressType, PartyStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PartyAddressPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PartyAddressPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PartyAddressPaginatedResult {
    pub data: Vec<PartyAddress>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PartyAddressFilter {
    pub party_id: Option<Uuid>,
    pub company_id: Option<Uuid>,
    pub address_type: Option<AddressType>,
    pub label: Option<String>,
    pub line1: Option<String>,
    pub line2: Option<String>,
    pub country_id: Option<Uuid>,
    pub province_id: Option<Uuid>,
    pub city_id: Option<Uuid>,
    pub district_id: Option<Uuid>,
    pub subdistrict_id: Option<Uuid>,
    pub postal_code: Option<String>,
    pub is_primary: Option<bool>,
    pub is_billing: Option<bool>,
    pub is_shipping: Option<bool>,
    pub status: Option<PartyStatus>,
}

impl PartyAddressFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.party_id.is_some() || self.company_id.is_some() || self.address_type.is_some() || self.label.is_some() || self.line1.is_some() || self.line2.is_some() || self.country_id.is_some() || self.province_id.is_some() || self.city_id.is_some() || self.district_id.is_some() || self.subdistrict_id.is_some() || self.postal_code.is_some() || self.is_primary.is_some() || self.is_billing.is_some() || self.is_shipping.is_some() || self.status.is_some()
    }
}

/// Repository trait for PartyAddress aggregate
///
/// This trait defines the persistence contract for PartyAddress entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PartyAddressRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new party_address entity
    async fn save(&self, entity: &PartyAddress) -> Result<PartyAddress>;

    /// Find party_address by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PartyAddress>>;

    /// Find all party_address entities
    async fn find_all(&self) -> Result<Vec<PartyAddress>>;

    /// Update party_address by ID
    async fn update(&self, id: &str, entity: &PartyAddress) -> Result<Option<PartyAddress>>;

    /// Delete party_address by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List party_address with pagination
    async fn list(&self, params: PartyAddressPaginationParams) -> Result<PartyAddressPaginatedResult>;

    /// List party_address with pagination and filters
    async fn list_with_filters(&self, params: PartyAddressPaginationParams, filters: PartyAddressFilter) -> Result<PartyAddressPaginatedResult>;

    /// Count all party_address entities
    async fn count(&self) -> Result<u64>;

    /// Count party_address entities matching filters
    async fn count_with_filters(&self, filters: PartyAddressFilter) -> Result<u64>;

    /// Check if party_address exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete party_address by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted party_address by ID
    async fn restore(&self, id: &str) -> Result<Option<PartyAddress>>;

    /// List soft-deleted party_address entities
    async fn list_deleted(&self, params: PartyAddressPaginationParams) -> Result<PartyAddressPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save party_address entities
    async fn bulk_save(&self, entities: &[PartyAddress]) -> Result<Vec<PartyAddress>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
