//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod party_repository;
mod party_address_repository;
mod party_contact_repository;
mod party_email_repository;
mod party_phone_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use party_repository::PartyRepository;
pub use party_address_repository::PartyAddressRepository;
pub use party_contact_repository::PartyContactRepository;
pub use party_email_repository::PartyEmailRepository;
pub use party_phone_repository::PartyPhoneRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// END CUSTOM
