//! Repository for PartyContact entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PartyContact, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::PartyContact;

/// Table name for PartyContact entities
pub const TABLE_NAME: &str = "party.party_contacts";

/// Repository for PartyContact entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PartyContactRepository(
    backbone_orm::GenericCrudRepository<PartyContact, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PartyContactRepository {
    type Target = backbone_orm::GenericCrudRepository<PartyContact, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PartyContactRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(PartyContactRepository, PartyContact, soft_delete);
