//! Repository for PartyPhone entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PartyPhone, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::PartyPhone;

/// Table name for PartyPhone entities
pub const TABLE_NAME: &str = "party.party_phones";

/// Repository for PartyPhone entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PartyPhoneRepository(
    backbone_orm::GenericCrudRepository<PartyPhone, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PartyPhoneRepository {
    type Target = backbone_orm::GenericCrudRepository<PartyPhone, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PartyPhoneRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(PartyPhoneRepository, PartyPhone, soft_delete);
