//! Repository for PartyEmail entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the validated write path's email SQL (4-layer rule: services orchestrate, repos
//! hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PartyEmail, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use sqlx::{PgConnection, PgPool};
use uuid::Uuid;

use crate::domain::entity::PartyEmail;

/// Table name for PartyEmail entities
pub const TABLE_NAME: &str = "party.party_emails";

/// Repository for PartyEmail entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PartyEmailRepository(
    backbone_orm::GenericCrudRepository<PartyEmail, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PartyEmailRepository {
    type Target = backbone_orm::GenericCrudRepository<PartyEmail, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PartyEmailRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a validated-email insert writes.
pub struct NewPartyEmailRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub party_id: Uuid,
    pub label: &'a str,
    pub email: &'a str,
    pub is_primary: bool,
}

/// Party-email write-path SQL. Lives here (not in the service) per the module's 4-layer rule.
impl PartyEmailRepository {
    /// Insert an email on the caller's pool. The caller has already established the company scope.
    pub async fn insert_from_new(
        &self,
        pool: &PgPool,
        r: &NewPartyEmailRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            "INSERT INTO party.party_emails (id, company_id, party_id, label, email, is_primary) \
             VALUES ($1,$2,$3,$4,$5,$6)",
        )
        .bind(r.id)
        .bind(r.company_id)
        .bind(r.party_id)
        .bind(r.label)
        .bind(r.email)
        .bind(r.is_primary)
        .execute(pool)
        .await?;
        Ok(())
    }

    /// Clear `is_primary` on every email row for `party_id` (including soft-deleted rows).
    /// Runs on the caller's tx — the caller has already bound the company on `conn`.
    pub async fn clear_primary_for_party(
        &self,
        conn: &mut PgConnection,
        party_id: Uuid,
        company_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let r = sqlx::query(
            "UPDATE party.party_emails SET is_primary = FALSE \
             WHERE party_id = $1 AND company_id = $2",
        )
        .bind(party_id)
        .bind(company_id)
        .execute(conn)
        .await?;
        Ok(r.rows_affected())
    }

    /// Set `is_primary = TRUE` on a single email. Runs on the caller's tx — the caller has
    /// already bound the company on `conn`. Returns rows_affected (0 ⇒ no matching live row).
    pub async fn set_primary_child(
        &self,
        conn: &mut PgConnection,
        child_id: Uuid,
        party_id: Uuid,
        company_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let r = sqlx::query(
            "UPDATE party.party_emails SET is_primary = TRUE \
             WHERE id = $1 AND party_id = $2 AND company_id = $3 AND (metadata->>'deleted_at') IS NULL",
        )
        .bind(child_id)
        .bind(party_id)
        .bind(company_id)
        .execute(conn)
        .await?;
        Ok(r.rows_affected())
    }
}

backbone_core::impl_crud_repository!(PartyEmailRepository, PartyEmail, soft_delete);
