//! Repository for PartyAddress entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PartyAddress, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::PartyAddress;

/// Table name for PartyAddress entities
pub const TABLE_NAME: &str = "party.party_addresses";

/// Repository for PartyAddress entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PartyAddressRepository(
    backbone_orm::GenericCrudRepository<PartyAddress, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PartyAddressRepository {
    type Target = backbone_orm::GenericCrudRepository<PartyAddress, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PartyAddressRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(PartyAddressRepository, PartyAddress, soft_delete);
