//! Repository for PartyContact entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the validated write path's contact SQL (4-layer rule: services orchestrate, repos
//! hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PartyContact, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use sqlx::{PgConnection, PgPool};
use uuid::Uuid;

use crate::domain::entity::PartyContact;

/// Table name for PartyContact entities
pub const TABLE_NAME: &str = "party.party_contacts";

/// Repository for PartyContact entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PartyContactRepository(
    backbone_orm::GenericCrudRepository<PartyContact, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PartyContactRepository {
    type Target = backbone_orm::GenericCrudRepository<PartyContact, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PartyContactRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a validated-contact insert writes.
pub struct NewPartyContactRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub party_id: Uuid,
    pub name: &'a str,
    pub job_title: Option<&'a str>,
    pub department: Option<&'a str>,
    pub email: Option<&'a str>,
    pub phone: Option<&'a str>,
    pub is_primary: bool,
}

/// Party-contact write-path SQL. Lives here (not in the service) per the module's 4-layer rule.
impl PartyContactRepository {
    /// Insert a contact, scoped so the RLS WITH CHECK sees `app.company_id` (a raw
    /// `.execute(pool)` lands on an unfenced pooled connection and a non-owner role is rejected).
    pub async fn insert_from_new(
        &self,
        pool: &PgPool,
        r: &NewPartyContactRow<'_>,
    ) -> Result<(), sqlx::Error> {
        backbone_orm::company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO party.party_contacts
                    (id, company_id, party_id, name, job_title, department, email, phone, is_primary)
                   VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)"#,
            )
            .bind(r.id)
            .bind(r.company_id)
            .bind(r.party_id)
            .bind(r.name)
            .bind(r.job_title)
            .bind(r.department)
            .bind(r.email)
            .bind(r.phone)
            .bind(r.is_primary),
        )
        .await?;
        Ok(())
    }

    /// Clear `is_primary` on every contact row for `party_id` (including soft-deleted rows).
    /// Runs on the caller's tx — the caller has already bound the company on `conn`.
    pub async fn clear_primary_for_party(
        &self,
        conn: &mut PgConnection,
        party_id: Uuid,
        company_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let r = sqlx::query(
            "UPDATE party.party_contacts SET is_primary = FALSE \
             WHERE party_id = $1 AND company_id = $2",
        )
        .bind(party_id)
        .bind(company_id)
        .execute(conn)
        .await?;
        Ok(r.rows_affected())
    }

    /// Set `is_primary = TRUE` on a single contact. Runs on the caller's tx — the caller has
    /// already bound the company on `conn`. Returns rows_affected (0 ⇒ no matching live row).
    pub async fn set_primary_child(
        &self,
        conn: &mut PgConnection,
        child_id: Uuid,
        party_id: Uuid,
        company_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let r = sqlx::query(
            "UPDATE party.party_contacts SET is_primary = TRUE \
             WHERE id = $1 AND party_id = $2 AND company_id = $3 AND (metadata->>'deleted_at') IS NULL",
        )
        .bind(child_id)
        .bind(party_id)
        .bind(company_id)
        .execute(conn)
        .await?;
        Ok(r.rows_affected())
    }
}

backbone_core::impl_crud_repository!(PartyContactRepository, PartyContact, soft_delete);
