//! Repository for PartyAddress entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the validated write path's address SQL (4-layer rule: services orchestrate, repos
//! hold SQL).
//!
//! Tenancy (ADR-0029): the SQL here carries no tenant key. The scoped-execute helper rides the
//! request-dedicated connection when the composing service bound one (its fence variables govern
//! what the RLS layer accepts) and falls back to a plain pool execute otherwise.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PartyAddress, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use rust_decimal::Decimal;
use sqlx::{PgConnection, PgPool};
use uuid::Uuid;

use crate::domain::entity::PartyAddress;

/// Table name for PartyAddress entities
pub const TABLE_NAME: &str = "party.party_addresses";

/// Repository for PartyAddress entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PartyAddressRepository(
    backbone_orm::GenericCrudRepository<PartyAddress, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PartyAddressRepository {
    type Target = backbone_orm::GenericCrudRepository<PartyAddress, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PartyAddressRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a validated-address insert writes.
pub struct NewPartyAddressRow<'a> {
    pub id: Uuid,
    pub party_id: Uuid,
    pub address_type: &'a str,
    pub label: Option<&'a str>,
    pub line1: &'a str,
    pub line2: Option<&'a str>,
    pub country_id: Option<Uuid>,
    pub province_id: Option<Uuid>,
    pub city_id: Option<Uuid>,
    pub district_id: Option<Uuid>,
    pub subdistrict_id: Option<Uuid>,
    pub postal_code: Option<&'a str>,
    pub latitude: Option<Decimal>,
    pub longitude: Option<Decimal>,
    pub is_primary: bool,
    pub is_billing: bool,
    pub is_shipping: bool,
}

/// Party-address write-path SQL. Lives here (not in the service) per the module's 4-layer rule.
impl PartyAddressRepository {
    /// Insert an address. Rides the request-dedicated connection when the composing service bound
    /// a scope — under a decorated deployment the fence's WITH CHECK governs the row; with no scope
    /// bound this is a plain insert.
    pub async fn insert_from_new(
        &self,
        pool: &PgPool,
        r: &NewPartyAddressRow<'_>,
    ) -> Result<(), sqlx::Error> {
        backbone_orm::org_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO party.party_addresses
                    (id, party_id, address_type, label, line1, line2, country_id, province_id,
                     city_id, district_id, subdistrict_id, postal_code, latitude, longitude, is_primary,
                     is_billing, is_shipping, status)
                   VALUES ($1,$2,$3::address_type,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,'active'::party_status)"#,
            )
            .bind(r.id)
            .bind(r.party_id)
            .bind(r.address_type)
            .bind(r.label)
            .bind(r.line1)
            .bind(r.line2)
            .bind(r.country_id)
            .bind(r.province_id)
            .bind(r.city_id)
            .bind(r.district_id)
            .bind(r.subdistrict_id)
            .bind(r.postal_code)
            .bind(r.latitude)
            .bind(r.longitude)
            .bind(r.is_primary)
            .bind(r.is_billing)
            .bind(r.is_shipping),
        )
        .await?;
        Ok(())
    }

    /// Clear `is_primary` on every address row for `party_id` (including soft-deleted rows, so a
    /// revival can never re-enter with two primaries). Runs on the caller's tx.
    pub async fn clear_primary_for_party(
        &self,
        conn: &mut PgConnection,
        party_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let r = sqlx::query(
            "UPDATE party.party_addresses SET is_primary = FALSE \
             WHERE party_id = $1",
        )
        .bind(party_id)
        .execute(conn)
        .await?;
        Ok(r.rows_affected())
    }

    /// Set `is_primary = TRUE` on a single address, scoped to (id, party_id) and excluding
    /// soft-deleted rows. Runs on the caller's tx. Returns rows_affected (0 ⇒ no matching live
    /// row).
    pub async fn set_primary_child(
        &self,
        conn: &mut PgConnection,
        child_id: Uuid,
        party_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let r = sqlx::query(
            "UPDATE party.party_addresses SET is_primary = TRUE \
             WHERE id = $1 AND party_id = $2 AND (metadata->>'deleted_at') IS NULL",
        )
        .bind(child_id)
        .bind(party_id)
        .execute(conn)
        .await?;
        Ok(r.rows_affected())
    }
}

backbone_core::impl_crud_repository!(PartyAddressRepository, PartyAddress, soft_delete);
