//! Repository for Party entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the validated write path's party SQL (4-layer rule: services orchestrate, repos hold
//! SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Party, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use sqlx::{PgPool, Row};
use uuid::Uuid;

use crate::domain::entity::Party;

/// Table name for Party entities
pub const TABLE_NAME: &str = "party.parties";

/// Repository for Party entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PartyRepository(
    backbone_orm::GenericCrudRepository<Party, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PartyRepository {
    type Target = backbone_orm::GenericCrudRepository<Party, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PartyRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a validated-party insert writes.
pub struct NewPartyRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub party_code: &'a str,
    pub party_kind: &'a str,
    pub name: &'a str,
    pub legal_name: Option<&'a str>,
    pub first_name: Option<&'a str>,
    pub last_name: Option<&'a str>,
    pub npwp: Option<&'a str>,
    pub nik: Option<&'a str>,
}

/// Party write-path SQL. Lives here (not in the service) per the module's 4-layer rule.
impl PartyRepository {
    /// Existence probe filtered by the caller's company. Runs through the scoped-execute helper so
    /// it rides the request-dedicated connection (or the task-local scope) — a raw `fetch_optional`
    /// lands on an unfenced pooled connection and the ADR-0008 fence returns nothing, even though
    /// the explicit `company_id=$2` filter matches. Soft-deleted rows are excluded.
    pub async fn find_active_id_in_company(
        &self,
        pool: &PgPool,
        id: Uuid,
        company_id: Uuid,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        let row = backbone_orm::company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                "SELECT id FROM party.parties \
                 WHERE id = $1 AND company_id = $2 AND (metadata->>'deleted_at') IS NULL",
            )
            .bind(id)
            .bind(company_id),
        )
        .await?;
        Ok(row.map(|r| r.get::<Uuid, _>("id")))
    }

    /// Insert a party, scoped so the RLS WITH CHECK sees `app.company_id`. A raw `.execute(pool)`
    /// runs on an unfenced pooled connection — under a non-owner role the shared_blank fence
    /// REJECTS the insert (silent 500 to the caller); the scoped helper rides the request
    /// connection (strong scope) or binds transaction-locally (task-local scope).
    pub async fn insert_from_new(
        &self,
        pool: &PgPool,
        r: &NewPartyRow<'_>,
    ) -> Result<(), sqlx::Error> {
        backbone_orm::company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO party.parties
                    (id, company_id, party_code, party_kind, name, legal_name, first_name, last_name,
                     npwp, nik, status)
                   VALUES ($1,$2,$3,$4::party_kind,$5,$6,$7,$8,$9,$10,'active'::party_status)"#,
            )
            .bind(r.id)
            .bind(r.company_id)
            .bind(r.party_code)
            .bind(r.party_kind)
            .bind(r.name)
            .bind(r.legal_name)
            .bind(r.first_name)
            .bind(r.last_name)
            .bind(r.npwp)
            .bind(r.nik),
        )
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(PartyRepository, Party, soft_delete);
