//! Repository for PartyPhone entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the validated write path's phone SQL (4-layer rule: services orchestrate, repos
//! hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PartyPhone, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use sqlx::{PgConnection, PgPool};
use uuid::Uuid;

use crate::domain::entity::PartyPhone;

/// Table name for PartyPhone entities
pub const TABLE_NAME: &str = "party.party_phones";

/// Repository for PartyPhone entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PartyPhoneRepository(
    backbone_orm::GenericCrudRepository<PartyPhone, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PartyPhoneRepository {
    type Target = backbone_orm::GenericCrudRepository<PartyPhone, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PartyPhoneRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a validated-phone insert writes.
pub struct NewPartyPhoneRow<'a> {
    pub id: Uuid,
    pub party_id: Uuid,
    pub label: &'a str,
    pub phone: &'a str,
    pub is_primary: bool,
}

/// Party-phone write-path SQL. Lives here (not in the service) per the module's 4-layer rule.
impl PartyPhoneRepository {
    /// Insert a phone. Rides the request-dedicated connection when the composing service bound
    /// a scope — under a decorated deployment the fence's WITH CHECK governs the row; with no scope
    /// bound this is a plain insert.
    pub async fn insert_from_new(
        &self,
        pool: &PgPool,
        r: &NewPartyPhoneRow<'_>,
    ) -> Result<(), sqlx::Error> {
        backbone_orm::org_scope::execute_scoped(
            pool,
            sqlx::query(
                "INSERT INTO party.party_phones (id, party_id, label, phone, is_primary) \
                 VALUES ($1,$2,$3,$4,$5)",
            )
            .bind(r.id)
            .bind(r.party_id)
            .bind(r.label)
            .bind(r.phone)
            .bind(r.is_primary),
        )
        .await?;
        Ok(())
    }

    /// Clear `is_primary` on every phone row for `party_id` (including soft-deleted rows).
    /// Runs on the caller's tx.
    pub async fn clear_primary_for_party(
        &self,
        conn: &mut PgConnection,
        party_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let r = sqlx::query(
            "UPDATE party.party_phones SET is_primary = FALSE \
             WHERE party_id = $1",
        )
        .bind(party_id)
        .execute(conn)
        .await?;
        Ok(r.rows_affected())
    }

    /// Set `is_primary = TRUE` on a single phone, excluding soft-deleted rows. Runs on the
    /// caller's tx. Returns rows_affected (0 ⇒ no matching live row).
    pub async fn set_primary_child(
        &self,
        conn: &mut PgConnection,
        child_id: Uuid,
        party_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let r = sqlx::query(
            "UPDATE party.party_phones SET is_primary = TRUE \
             WHERE id = $1 AND party_id = $2 AND (metadata->>'deleted_at') IS NULL",
        )
        .bind(child_id)
        .bind(party_id)
        .execute(conn)
        .await?;
        Ok(r.rows_affected())
    }
}

backbone_core::impl_crud_repository!(PartyPhoneRepository, PartyPhone, soft_delete);
