//! Repository for PartyEmail entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PartyEmail, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::PartyEmail;

/// Table name for PartyEmail entities
pub const TABLE_NAME: &str = "party.party_emails";

/// Repository for PartyEmail entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PartyEmailRepository(
    backbone_orm::GenericCrudRepository<PartyEmail, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PartyEmailRepository {
    type Target = backbone_orm::GenericCrudRepository<PartyEmail, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PartyEmailRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(PartyEmailRepository, PartyEmail, soft_delete);
