//! Validator for PartyPhone entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PartyPhone>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::PartyPhone;

/// Validator type alias for PartyPhone entities.
pub type PartyPhoneValidator = EntityValidator<PartyPhone>;

/// Build a validator for PartyPhone with all schema-defined field rules.
pub fn party_phone_validator() -> PartyPhoneValidator {
    EntityValidator::new()
        .rule(RequiredString::new("label", |e: &PartyPhone| &e.label))
        .rule(RequiredString::new("phone", |e: &PartyPhone| &e.phone))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
