//! Validator for PartyEmail entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PartyEmail>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::PartyEmail;

/// Validator type alias for PartyEmail entities.
pub type PartyEmailValidator = EntityValidator<PartyEmail>;

/// Build a validator for PartyEmail with all schema-defined field rules.
pub fn party_email_validator() -> PartyEmailValidator {
    EntityValidator::new()
        .rule(RequiredString::new("label", |e: &PartyEmail| &e.label))
        .rule(RequiredString::new("email", |e: &PartyEmail| &e.email))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
