//! Validator for Party entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Party>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::Party;

/// Validator type alias for Party entities.
pub type PartyValidator = EntityValidator<Party>;

/// Build a validator for Party with all schema-defined field rules.
pub fn party_validator() -> PartyValidator {
    EntityValidator::new()
        .rule(RequiredString::new("party_code", |e: &Party| &e.party_code))
        .rule(RequiredString::new("name", |e: &Party| &e.name))
        .rule(OptionalNotBlank::new("legal_name", |e: &Party| e.legal_name.as_deref()))
        .rule(OptionalNotBlank::new("first_name", |e: &Party| e.first_name.as_deref()))
        .rule(OptionalNotBlank::new("last_name", |e: &Party| e.last_name.as_deref()))
        .rule(OptionalNotBlank::new("npwp", |e: &Party| e.npwp.as_deref()))
        .rule(OptionalNotBlank::new("nik", |e: &Party| e.nik.as_deref()))
        .rule(OptionalNotBlank::new("notes", |e: &Party| e.notes.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
