//! Validator for PartyContact entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PartyContact>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::PartyContact;

/// Validator type alias for PartyContact entities.
pub type PartyContactValidator = EntityValidator<PartyContact>;

/// Build a validator for PartyContact with all schema-defined field rules.
pub fn party_contact_validator() -> PartyContactValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &PartyContact| &e.name))
        .rule(OptionalNotBlank::new("job_title", |e: &PartyContact| e.job_title.as_deref()))
        .rule(OptionalNotBlank::new("department", |e: &PartyContact| e.department.as_deref()))
        .rule(OptionalNotBlank::new("email", |e: &PartyContact| e.email.as_deref()))
        .rule(OptionalNotBlank::new("phone", |e: &PartyContact| e.phone.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
