//! Validator for PartyAddress entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PartyAddress>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::PartyAddress;

/// Validator type alias for PartyAddress entities.
pub type PartyAddressValidator = EntityValidator<PartyAddress>;

/// Build a validator for PartyAddress with all schema-defined field rules.
pub fn party_address_validator() -> PartyAddressValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("label", |e: &PartyAddress| e.label.as_deref()))
        .rule(RequiredString::new("line1", |e: &PartyAddress| &e.line1))
        .rule(OptionalNotBlank::new("line2", |e: &PartyAddress| e.line2.as_deref()))
        .rule(OptionalNotBlank::new("postal_code", |e: &PartyAddress| e.postal_code.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
