//! Auth configuration for PartyPhone handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<PartyPhone>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::PartyPhoneService;
use crate::domain::entity::PartyPhone;

/// Permission string constants for PartyPhone operations.
pub mod permissions {
    pub const LIST:        &str = "party_phone:list";
    pub const READ:        &str = "party_phone:read";
    pub const CREATE:      &str = "party_phone:create";
    pub const UPDATE:      &str = "party_phone:update";
    pub const DELETE:      &str = "party_phone:delete";
    pub const RESTORE:     &str = "party_phone:restore";
    pub const TRASH:       &str = "party_phone:trash";
    pub const EMPTY_TRASH: &str = "party_phone:empty_trash";
    pub const BULK_CREATE: &str = "party_phone:bulk_create";
    pub const UPSERT:      &str = "party_phone:upsert";
}

/// Resource policy for PartyPhone — maps CRUD actions to permission strings.
pub struct PartyPhonePolicy;

#[async_trait]
impl ResourcePolicy<PartyPhone> for PartyPhonePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &PartyPhone,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for PartyPhone handlers.
///
/// Wraps `PartyPhoneService` and checks `PartyPhonePolicy` before delegating.
pub type PartyPhoneGuard = PermissionGuard<PartyPhone>;

/// Service-integrated permission guard for PartyPhone (for use in generated handlers).
pub type PartyPhoneServiceGuard = ServicePermissionGuard<PartyPhone, PartyPhoneService, PartyPhonePolicy>;

// <<< CUSTOM
// END CUSTOM
