//! Auth configuration for PartyEmail handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<PartyEmail>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::PartyEmailService;
use crate::domain::entity::PartyEmail;

/// Permission string constants for PartyEmail operations.
pub mod permissions {
    pub const LIST:        &str = "party_email:list";
    pub const READ:        &str = "party_email:read";
    pub const CREATE:      &str = "party_email:create";
    pub const UPDATE:      &str = "party_email:update";
    pub const DELETE:      &str = "party_email:delete";
    pub const RESTORE:     &str = "party_email:restore";
    pub const TRASH:       &str = "party_email:trash";
    pub const EMPTY_TRASH: &str = "party_email:empty_trash";
    pub const BULK_CREATE: &str = "party_email:bulk_create";
    pub const UPSERT:      &str = "party_email:upsert";
}

/// Resource policy for PartyEmail — maps CRUD actions to permission strings.
pub struct PartyEmailPolicy;

#[async_trait]
impl ResourcePolicy<PartyEmail> for PartyEmailPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &PartyEmail,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for PartyEmail handlers.
///
/// Wraps `PartyEmailService` and checks `PartyEmailPolicy` before delegating.
pub type PartyEmailGuard = PermissionGuard<PartyEmail>;

/// Service-integrated permission guard for PartyEmail (for use in generated handlers).
pub type PartyEmailServiceGuard = ServicePermissionGuard<PartyEmail, PartyEmailService, PartyEmailPolicy>;

// <<< CUSTOM
// END CUSTOM
