//! Auth configuration for PartyAddress handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<PartyAddress>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::PartyAddressService;
use crate::domain::entity::PartyAddress;

/// Permission string constants for PartyAddress operations.
pub mod permissions {
    pub const LIST:        &str = "party_address:list";
    pub const READ:        &str = "party_address:read";
    pub const CREATE:      &str = "party_address:create";
    pub const UPDATE:      &str = "party_address:update";
    pub const DELETE:      &str = "party_address:delete";
    pub const RESTORE:     &str = "party_address:restore";
    pub const TRASH:       &str = "party_address:trash";
    pub const EMPTY_TRASH: &str = "party_address:empty_trash";
    pub const BULK_CREATE: &str = "party_address:bulk_create";
    pub const UPSERT:      &str = "party_address:upsert";
}

/// Resource policy for PartyAddress — maps CRUD actions to permission strings.
pub struct PartyAddressPolicy;

#[async_trait]
impl ResourcePolicy<PartyAddress> for PartyAddressPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &PartyAddress,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for PartyAddress handlers.
///
/// Wraps `PartyAddressService` and checks `PartyAddressPolicy` before delegating.
pub type PartyAddressGuard = PermissionGuard<PartyAddress>;

/// Service-integrated permission guard for PartyAddress (for use in generated handlers).
pub type PartyAddressServiceGuard = ServicePermissionGuard<PartyAddress, PartyAddressService, PartyAddressPolicy>;

// <<< CUSTOM
// END CUSTOM
