//! Auth configuration for PartyContact handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<PartyContact>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::PartyContactService;
use crate::domain::entity::PartyContact;

/// Permission string constants for PartyContact operations.
pub mod permissions {
    pub const LIST:        &str = "party_contact:list";
    pub const READ:        &str = "party_contact:read";
    pub const CREATE:      &str = "party_contact:create";
    pub const UPDATE:      &str = "party_contact:update";
    pub const DELETE:      &str = "party_contact:delete";
    pub const RESTORE:     &str = "party_contact:restore";
    pub const TRASH:       &str = "party_contact:trash";
    pub const EMPTY_TRASH: &str = "party_contact:empty_trash";
    pub const BULK_CREATE: &str = "party_contact:bulk_create";
    pub const UPSERT:      &str = "party_contact:upsert";
}

/// Resource policy for PartyContact — maps CRUD actions to permission strings.
pub struct PartyContactPolicy;

#[async_trait]
impl ResourcePolicy<PartyContact> for PartyContactPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &PartyContact,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for PartyContact handlers.
///
/// Wraps `PartyContactService` and checks `PartyContactPolicy` before delegating.
pub type PartyContactGuard = PermissionGuard<PartyContact>;

/// Service-integrated permission guard for PartyContact (for use in generated handlers).
pub type PartyContactServiceGuard = ServicePermissionGuard<PartyContact, PartyContactService, PartyContactPolicy>;

// <<< CUSTOM
// END CUSTOM
