//! Auth configuration for Party handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Party>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::PartyService;
use crate::domain::entity::Party;

/// Permission string constants for Party operations.
pub mod permissions {
    pub const LIST:        &str = "party:list";
    pub const READ:        &str = "party:read";
    pub const CREATE:      &str = "party:create";
    pub const UPDATE:      &str = "party:update";
    pub const DELETE:      &str = "party:delete";
    pub const RESTORE:     &str = "party:restore";
    pub const TRASH:       &str = "party:trash";
    pub const EMPTY_TRASH: &str = "party:empty_trash";
    pub const BULK_CREATE: &str = "party:bulk_create";
    pub const UPSERT:      &str = "party:upsert";
}

/// Resource policy for Party — maps CRUD actions to permission strings.
pub struct PartyPolicy;

#[async_trait]
impl ResourcePolicy<Party> for PartyPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Party,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Party handlers.
///
/// Wraps `PartyService` and checks `PartyPolicy` before delegating.
pub type PartyGuard = PermissionGuard<Party>;

/// Service-integrated permission guard for Party (for use in generated handlers).
pub type PartyServiceGuard = ServicePermissionGuard<Party, PartyService, PartyPolicy>;

// <<< CUSTOM
// END CUSTOM
