//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod party_api_test;
pub mod party_address_api_test;
pub mod party_contact_api_test;
pub mod party_email_api_test;
pub mod party_phone_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use party_api_test::*;
pub use party_address_api_test::*;
pub use party_contact_api_test::*;
pub use party_email_api_test::*;
pub use party_phone_api_test::*;
