//! Party API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Party CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// PARTY TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Party
pub struct PartyTestData;

impl TestDataGenerator for PartyTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "party_code": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "party_kind": "organization",
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "legal_name": null,
            "first_name": null,
            "last_name": null,
            "npwp": null,
            "nik": null,
            "status": "active",
            "notes": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "party_code": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "party_kind": "organization",
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "legal_name": null,
            "first_name": null,
            "last_name": null,
            "npwp": null,
            "nik": null,
            "status": "active",
            "notes": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// PARTY API TEST
// ============================================================================

/// Party API test suite
pub struct PartyApiTest {
    inner: GenericCrudTest<PartyTestData>,
}

impl PartyApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/parties", "Party");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, PartyTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for PartyApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_party_crud() {
        let mut test = PartyApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Party specific tests here
// <<< CUSTOM TESTS END >>>
