//! PartyEmail API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the PartyEmail CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// PARTYEMAIL TEST DATA GENERATOR
// ============================================================================

/// Test data generator for PartyEmail
pub struct PartyEmailTestData;

impl TestDataGenerator for PartyEmailTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "party_id": Uuid::new_v4().to_string(),
            "label": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "email": format!("test{}@example.com", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "is_primary": false,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "party_id": Uuid::new_v4().to_string(),
            "label": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "email": format!("test{}@example.com", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "is_primary": false,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/parties", &super::party_api_test::PartyTestData).await {
            deps.push(("party_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// PARTYEMAIL API TEST
// ============================================================================

/// PartyEmail API test suite
pub struct PartyEmailApiTest {
    inner: GenericCrudTest<PartyEmailTestData>,
}

impl PartyEmailApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/party_emails", "PartyEmail");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, PartyEmailTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for PartyEmailApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_party_email_crud() {
        let mut test = PartyEmailApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add PartyEmail specific tests here
// <<< CUSTOM TESTS END >>>
