//! PartyAddress API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the PartyAddress CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// PARTYADDRESS TEST DATA GENERATOR
// ============================================================================

/// Test data generator for PartyAddress
pub struct PartyAddressTestData;

impl TestDataGenerator for PartyAddressTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "party_id": Uuid::new_v4().to_string(),
            "address_type": "billing",
            "label": null,
            "line1": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "line2": null,
            "country_id": null,
            "province_id": null,
            "city_id": null,
            "district_id": null,
            "subdistrict_id": null,
            "postal_code": null,
            "latitude": null,
            "longitude": null,
            "is_primary": false,
            "is_billing": false,
            "is_shipping": false,
            "status": "active",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "party_id": Uuid::new_v4().to_string(),
            "address_type": "billing",
            "label": null,
            "line1": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "line2": null,
            "country_id": null,
            "province_id": null,
            "city_id": null,
            "district_id": null,
            "subdistrict_id": null,
            "postal_code": null,
            "latitude": null,
            "longitude": null,
            "is_primary": false,
            "is_billing": false,
            "is_shipping": false,
            "status": "active",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/parties", &super::party_api_test::PartyTestData).await {
            deps.push(("party_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// PARTYADDRESS API TEST
// ============================================================================

/// PartyAddress API test suite
pub struct PartyAddressApiTest {
    inner: GenericCrudTest<PartyAddressTestData>,
}

impl PartyAddressApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/party_addresses", "PartyAddress");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, PartyAddressTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for PartyAddressApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_party_address_crud() {
        let mut test = PartyAddressApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add PartyAddress specific tests here
// <<< CUSTOM TESTS END >>>
