//! Party Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::PartyService;
use crate::application::service::PartyAddressService;
use crate::application::service::PartyContactService;
use crate::application::service::PartyEmailService;
use crate::application::service::PartyPhoneService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Party service
    pub party_service: Arc<PartyService>,
    /// PartyAddress service
    pub party_address_service: Arc<PartyAddressService>,
    /// PartyContact service
    pub party_contact_service: Arc<PartyContactService>,
    /// PartyEmail service
    pub party_email_service: Arc<PartyEmailService>,
    /// PartyPhone service
    pub party_phone_service: Arc<PartyPhoneService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        party_service: Arc<PartyService>,
        party_address_service: Arc<PartyAddressService>,
        party_contact_service: Arc<PartyContactService>,
        party_email_service: Arc<PartyEmailService>,
        party_phone_service: Arc<PartyPhoneService>
    ) -> Self {
        Self {
            party_service,
            party_address_service,
            party_contact_service,
            party_email_service,
            party_phone_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::PartyModule) -> Self {
        Self {
            party_service: module.party_service.clone(),
            party_address_service: module.party_address_service.clone(),
            party_contact_service: module.party_contact_service.clone(),
            party_email_service: module.party_email_service.clone(),
            party_phone_service: module.party_phone_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    party_service: Option<Arc<PartyService>>,
    party_address_service: Option<Arc<PartyAddressService>>,
    party_contact_service: Option<Arc<PartyContactService>>,
    party_email_service: Option<Arc<PartyEmailService>>,
    party_phone_service: Option<Arc<PartyPhoneService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Party service.
    pub fn with_party_service(mut self, service: Arc<PartyService>) -> Self {
        self.party_service = Some(service);
        self
    }

    /// Set the PartyAddress service.
    pub fn with_party_address_service(mut self, service: Arc<PartyAddressService>) -> Self {
        self.party_address_service = Some(service);
        self
    }

    /// Set the PartyContact service.
    pub fn with_party_contact_service(mut self, service: Arc<PartyContactService>) -> Self {
        self.party_contact_service = Some(service);
        self
    }

    /// Set the PartyEmail service.
    pub fn with_party_email_service(mut self, service: Arc<PartyEmailService>) -> Self {
        self.party_email_service = Some(service);
        self
    }

    /// Set the PartyPhone service.
    pub fn with_party_phone_service(mut self, service: Arc<PartyPhoneService>) -> Self {
        self.party_phone_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            party_service: self.party_service.expect("party_service is required"),
            party_address_service: self.party_address_service.expect("party_address_service is required"),
            party_contact_service: self.party_contact_service.expect("party_contact_service is required"),
            party_email_service: self.party_email_service.expect("party_email_service is required"),
            party_phone_service: self.party_phone_service.expect("party_phone_service is required"),
        }
    }
}
