//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    party_handler::create_party_routes,
    party_address_handler::create_party_address_routes,
    party_contact_handler::create_party_contact_routes,
    party_email_handler::create_party_email_routes,
    party_phone_handler::create_party_phone_routes,
};

use crate::application::service::{
    PartyService,
    PartyAddressService,
    PartyContactService,
    PartyEmailService,
    PartyPhoneService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub party: Arc<PartyService>,
    pub party_address: Arc<PartyAddressService>,
    pub party_contact: Arc<PartyContactService>,
    pub party_email: Arc<PartyEmailService>,
    pub party_phone: Arc<PartyPhoneService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // Party routes (12 Backbone endpoints)
        .merge(create_party_routes(services.party))
        // PartyAddress routes (12 Backbone endpoints)
        .merge(create_party_address_routes(services.party_address))
        // PartyContact routes (12 Backbone endpoints)
        .merge(create_party_contact_routes(services.party_contact))
        // PartyEmail routes (12 Backbone endpoints)
        .merge(create_party_email_routes(services.party_email))
        // PartyPhone routes (12 Backbone endpoints)
        .merge(create_party_phone_routes(services.party_phone))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn party_routes(service: Arc<PartyService>) -> Router {
        create_party_routes(service)
    }

    pub fn party_address_routes(service: Arc<PartyAddressService>) -> Router {
        create_party_address_routes(service)
    }

    pub fn party_contact_routes(service: Arc<PartyContactService>) -> Router {
        create_party_contact_routes(service)
    }

    pub fn party_email_routes(service: Arc<PartyEmailService>) -> Router {
        create_party_email_routes(service)
    }

    pub fn party_phone_routes(service: Arc<PartyPhoneService>) -> Router {
        create_party_phone_routes(service)
    }

}
