//! Public events for Party module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// PARTY EVENTS
// ============================================================================

/// Event published when a Party is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyCreatedEvent {
    pub id: PartyId,
    pub data: PartyDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Party is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyUpdatedEvent {
    pub id: PartyId,
    pub data: PartyDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Party is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyDeletedEvent {
    pub id: PartyId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PARTYADDRESS EVENTS
// ============================================================================

/// Event published when a PartyAddress is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyAddressCreatedEvent {
    pub id: PartyAddressId,
    pub data: PartyAddressDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PartyAddress is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyAddressUpdatedEvent {
    pub id: PartyAddressId,
    pub data: PartyAddressDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PartyAddress is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyAddressDeletedEvent {
    pub id: PartyAddressId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PARTYCONTACT EVENTS
// ============================================================================

/// Event published when a PartyContact is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyContactCreatedEvent {
    pub id: PartyContactId,
    pub data: PartyContactDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PartyContact is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyContactUpdatedEvent {
    pub id: PartyContactId,
    pub data: PartyContactDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PartyContact is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyContactDeletedEvent {
    pub id: PartyContactId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PARTYEMAIL EVENTS
// ============================================================================

/// Event published when a PartyEmail is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyEmailCreatedEvent {
    pub id: PartyEmailId,
    pub data: PartyEmailDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PartyEmail is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyEmailUpdatedEvent {
    pub id: PartyEmailId,
    pub data: PartyEmailDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PartyEmail is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyEmailDeletedEvent {
    pub id: PartyEmailId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PARTYPHONE EVENTS
// ============================================================================

/// Event published when a PartyPhone is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyPhoneCreatedEvent {
    pub id: PartyPhoneId,
    pub data: PartyPhoneDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PartyPhone is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyPhoneUpdatedEvent {
    pub id: PartyPhoneId,
    pub data: PartyPhoneDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a PartyPhone is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyPhoneDeletedEvent {
    pub id: PartyPhoneId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Party module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PartyEvent {
    PartyCreated(PartyCreatedEvent),
    PartyUpdated(PartyUpdatedEvent),
    PartyDeleted(PartyDeletedEvent),
    PartyAddressCreated(PartyAddressCreatedEvent),
    PartyAddressUpdated(PartyAddressUpdatedEvent),
    PartyAddressDeleted(PartyAddressDeletedEvent),
    PartyContactCreated(PartyContactCreatedEvent),
    PartyContactUpdated(PartyContactUpdatedEvent),
    PartyContactDeleted(PartyContactDeletedEvent),
    PartyEmailCreated(PartyEmailCreatedEvent),
    PartyEmailUpdated(PartyEmailUpdatedEvent),
    PartyEmailDeleted(PartyEmailDeletedEvent),
    PartyPhoneCreated(PartyPhoneCreatedEvent),
    PartyPhoneUpdated(PartyPhoneUpdatedEvent),
    PartyPhoneDeleted(PartyPhoneDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for PartyEventMetadata {
    fn default() -> Self {
        Self {
            module: "party",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
