//! Party Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Party exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use party::exports::{PartyDto, PartyQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `PartyDto` - Data transfer object for Party
/// - `PartySummary` - Summary view of Party
/// - `PartyId` - Type-safe ID wrapper
/// - `PartyAddressDto` - Data transfer object for PartyAddress
/// - `PartyAddressSummary` - Summary view of PartyAddress
/// - `PartyAddressId` - Type-safe ID wrapper
/// - `PartyContactDto` - Data transfer object for PartyContact
/// - `PartyContactSummary` - Summary view of PartyContact
/// - `PartyContactId` - Type-safe ID wrapper
/// - `PartyEmailDto` - Data transfer object for PartyEmail
/// - `PartyEmailSummary` - Summary view of PartyEmail
/// - `PartyEmailId` - Type-safe ID wrapper
/// - `PartyPhoneDto` - Data transfer object for PartyPhone
/// - `PartyPhoneSummary` - Summary view of PartyPhone
/// - `PartyPhoneId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `PartyQueryService` - Read-only queries
///
/// ## Public Events
/// - `PartyCreatedEvent` - Published when Party is created
/// - `PartyUpdatedEvent` - Published when Party is updated
/// - `PartyDeletedEvent` - Published when Party is deleted
/// - `PartyAddressCreatedEvent` - Published when PartyAddress is created
/// - `PartyAddressUpdatedEvent` - Published when PartyAddress is updated
/// - `PartyAddressDeletedEvent` - Published when PartyAddress is deleted
/// - `PartyContactCreatedEvent` - Published when PartyContact is created
/// - `PartyContactUpdatedEvent` - Published when PartyContact is updated
/// - `PartyContactDeletedEvent` - Published when PartyContact is deleted
/// - `PartyEmailCreatedEvent` - Published when PartyEmail is created
/// - `PartyEmailUpdatedEvent` - Published when PartyEmail is updated
/// - `PartyEmailDeletedEvent` - Published when PartyEmail is deleted
/// - `PartyPhoneCreatedEvent` - Published when PartyPhone is created
/// - `PartyPhoneUpdatedEvent` - Published when PartyPhone is updated
/// - `PartyPhoneDeletedEvent` - Published when PartyPhone is deleted
pub struct ExportSummary;
