//! Public services for Party module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Party module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait PartyQueryService: Send + Sync {
    /// Get Party by ID
    async fn get_party(&self, id: PartyId) -> Result<Option<PartyDto>>;

    /// Get Party summary by ID
    async fn get_party_summary(&self, id: PartyId) -> Result<Option<PartySummary>>;

    /// Check if Party exists
    async fn party_exists(&self, id: PartyId) -> Result<bool>;

    /// Get PartyAddress by ID
    async fn get_party_address(&self, id: PartyAddressId) -> Result<Option<PartyAddressDto>>;

    /// Get PartyAddress summary by ID
    async fn get_party_address_summary(&self, id: PartyAddressId) -> Result<Option<PartyAddressSummary>>;

    /// Check if PartyAddress exists
    async fn party_address_exists(&self, id: PartyAddressId) -> Result<bool>;

    /// Get PartyContact by ID
    async fn get_party_contact(&self, id: PartyContactId) -> Result<Option<PartyContactDto>>;

    /// Get PartyContact summary by ID
    async fn get_party_contact_summary(&self, id: PartyContactId) -> Result<Option<PartyContactSummary>>;

    /// Check if PartyContact exists
    async fn party_contact_exists(&self, id: PartyContactId) -> Result<bool>;

    /// Get PartyEmail by ID
    async fn get_party_email(&self, id: PartyEmailId) -> Result<Option<PartyEmailDto>>;

    /// Get PartyEmail summary by ID
    async fn get_party_email_summary(&self, id: PartyEmailId) -> Result<Option<PartyEmailSummary>>;

    /// Check if PartyEmail exists
    async fn party_email_exists(&self, id: PartyEmailId) -> Result<bool>;

    /// Get PartyPhone by ID
    async fn get_party_phone(&self, id: PartyPhoneId) -> Result<Option<PartyPhoneDto>>;

    /// Get PartyPhone summary by ID
    async fn get_party_phone_summary(&self, id: PartyPhoneId) -> Result<Option<PartyPhoneSummary>>;

    /// Check if PartyPhone exists
    async fn party_phone_exists(&self, id: PartyPhoneId) -> Result<bool>;

}

// ============================================================================
// QUERY SERVICE IMPLEMENTATION
// ============================================================================

/// Default implementation of PartyQueryService
pub struct PartyQueryServiceImpl<R> {
    repository: Arc<R>,
}

impl<R> PartyQueryServiceImpl<R> {
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }
}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
