//! Public types for Party module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use crate::domain::entity::*;

// ============================================================================
// PARTY TYPES
// ============================================================================

/// Type-safe ID for Party
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PartyId(pub Uuid);

impl PartyId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PartyId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PartyId> for Uuid {
    fn from(id: PartyId) -> Self {
        id.0
    }
}

/// Data transfer object for Party
///
/// This is the public representation of Party for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyDto {
    pub id: PartyId,
    pub party_code: String,
    pub party_kind: PartyKind,
    pub name: String,
    pub legal_name: Option<String>,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub npwp: Option<String>,
    pub nik: Option<String>,
    pub status: PartyStatus,
    pub notes: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of Party for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartySummary {
    pub id: PartyId,
    pub name: String,
    pub legal_name: Option<String>,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub status: PartyStatus,
}

/// Reference to Party for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyRef {
    pub id: PartyId,
}

// ============================================================================
// PARTYADDRESS TYPES
// ============================================================================

/// Type-safe ID for PartyAddress
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PartyAddressId(pub Uuid);

impl PartyAddressId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PartyAddressId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PartyAddressId> for Uuid {
    fn from(id: PartyAddressId) -> Self {
        id.0
    }
}

/// Data transfer object for PartyAddress
///
/// This is the public representation of PartyAddress for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyAddressDto {
    pub id: PartyAddressId,
    pub party_id: Uuid,
    pub address_type: AddressType,
    pub label: Option<String>,
    pub line1: String,
    pub line2: Option<String>,
    pub country_id: Option<Uuid>,
    pub province_id: Option<Uuid>,
    pub city_id: Option<Uuid>,
    pub district_id: Option<Uuid>,
    pub subdistrict_id: Option<Uuid>,
    pub postal_code: Option<String>,
    pub latitude: Option<Decimal>,
    pub longitude: Option<Decimal>,
    pub is_primary: bool,
    pub is_billing: bool,
    pub is_shipping: bool,
    pub status: PartyStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of PartyAddress for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyAddressSummary {
    pub id: PartyAddressId,
    pub status: PartyStatus,
}

/// Reference to PartyAddress for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyAddressRef {
    pub id: PartyAddressId,
}

// ============================================================================
// PARTYCONTACT TYPES
// ============================================================================

/// Type-safe ID for PartyContact
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PartyContactId(pub Uuid);

impl PartyContactId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PartyContactId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PartyContactId> for Uuid {
    fn from(id: PartyContactId) -> Self {
        id.0
    }
}

/// Data transfer object for PartyContact
///
/// This is the public representation of PartyContact for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyContactDto {
    pub id: PartyContactId,
    pub party_id: Uuid,
    pub name: String,
    pub job_title: Option<String>,
    pub department: Option<String>,
    pub email: Option<String>,
    pub phone: Option<String>,
    pub is_primary: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of PartyContact for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyContactSummary {
    pub id: PartyContactId,
    pub name: String,
    pub email: Option<String>,
}

/// Reference to PartyContact for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyContactRef {
    pub id: PartyContactId,
}

// ============================================================================
// PARTYEMAIL TYPES
// ============================================================================

/// Type-safe ID for PartyEmail
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PartyEmailId(pub Uuid);

impl PartyEmailId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PartyEmailId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PartyEmailId> for Uuid {
    fn from(id: PartyEmailId) -> Self {
        id.0
    }
}

/// Data transfer object for PartyEmail
///
/// This is the public representation of PartyEmail for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyEmailDto {
    pub id: PartyEmailId,
    pub party_id: Uuid,
    pub label: String,
    pub email: String,
    pub is_primary: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of PartyEmail for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyEmailSummary {
    pub id: PartyEmailId,
    pub email: String,
}

/// Reference to PartyEmail for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyEmailRef {
    pub id: PartyEmailId,
}

// ============================================================================
// PARTYPHONE TYPES
// ============================================================================

/// Type-safe ID for PartyPhone
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PartyPhoneId(pub Uuid);

impl PartyPhoneId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PartyPhoneId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PartyPhoneId> for Uuid {
    fn from(id: PartyPhoneId) -> Self {
        id.0
    }
}

/// Data transfer object for PartyPhone
///
/// This is the public representation of PartyPhone for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyPhoneDto {
    pub id: PartyPhoneId,
    pub party_id: Uuid,
    pub label: String,
    pub phone: String,
    pub is_primary: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of PartyPhone for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyPhoneSummary {
    pub id: PartyPhoneId,
}

/// Reference to PartyPhone for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyPhoneRef {
    pub id: PartyPhoneId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
