//! Party Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::PartyService;
pub use application::service::PartyAddressService;
pub use application::service::PartyContactService;
pub use application::service::PartyEmailService;
pub use application::service::PartyPhoneService;

// <<< CUSTOM
pub use application::service::{
    validate_nik, validate_npwp, NewAddress, NewContact, NewEmail, NewParty, NewPhone,
    PartyWriteError, PartyWriteService,
};
pub use presentation::http::create_guarded_party_routes;
// END CUSTOM
use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Party module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let party = PartyModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = party.all_crud_routes();
/// ```
pub struct PartyModule {
    pub party_service: Arc<PartyService>,
    pub party_address_service: Arc<PartyAddressService>,
    pub party_contact_service: Arc<PartyContactService>,
    pub party_email_service: Arc<PartyEmailService>,
    pub party_phone_service: Arc<PartyPhoneService>,
    // <<< CUSTOM
    /// Validated party + child writes (NPWP/NIK format+uniqueness, party existence).
    pub party_write_service: Arc<PartyWriteService>,
    // END CUSTOM
}

impl PartyModule {
    /// Create a new module builder
    pub fn builder() -> PartyModuleBuilder {
        PartyModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_party_routes,
            create_party_address_routes,
            create_party_contact_routes,
            create_party_email_routes,
            create_party_phone_routes,
        };

        Router::new()
            .merge(create_party_routes(self.party_service.clone()))
            .merge(create_party_address_routes(self.party_address_service.clone()))
            .merge(create_party_contact_routes(self.party_contact_service.clone()))
            .merge(create_party_email_routes(self.party_email_service.clone()))
            .merge(create_party_phone_routes(self.party_phone_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD on every entity; compose a guarded router for production, or call all_crud_routes() for the intentional full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }
}

/// Builder for PartyModule
pub struct PartyModuleBuilder {
    db_pool: Option<PgPool>,
}

impl PartyModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<PartyModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Party service
        let party_repository = Arc::new(PartyRepository::new(db_pool.clone()));
        let party_service = Arc::new(PartyService::with_repository(party_repository.clone()));

        // PartyAddress service
        let party_address_repository = Arc::new(PartyAddressRepository::new(db_pool.clone()));
        let party_address_service = Arc::new(PartyAddressService::with_repository(party_address_repository.clone()));

        // PartyContact service
        let party_contact_repository = Arc::new(PartyContactRepository::new(db_pool.clone()));
        let party_contact_service = Arc::new(PartyContactService::with_repository(party_contact_repository.clone()));

        // PartyEmail service
        let party_email_repository = Arc::new(PartyEmailRepository::new(db_pool.clone()));
        let party_email_service = Arc::new(PartyEmailService::with_repository(party_email_repository.clone()));

        // PartyPhone service
        let party_phone_repository = Arc::new(PartyPhoneRepository::new(db_pool.clone()));
        let party_phone_service = Arc::new(PartyPhoneService::with_repository(party_phone_repository.clone()));

        // <<< CUSTOM
        let party_write_service = Arc::new(PartyWriteService::new(db_pool.clone()));
        // END CUSTOM

        Ok(PartyModule {
            party_service,
            party_address_service,
            party_contact_service,
            party_email_service,
            party_phone_service,
            // <<< CUSTOM
            party_write_service,
            // END CUSTOM
        })
    }
}

impl Default for PartyModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}