//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod party_usecases;
pub mod party_address_usecases;
pub mod party_contact_usecases;
pub mod party_email_usecases;
pub mod party_phone_usecases;

pub use party_usecases::{
    CreatePartyUseCase, UpdatePartyUseCase, GetPartyUseCase,
    DeletePartyUseCase, ListPartyUseCase,
};
pub use party_address_usecases::{
    CreatePartyAddressUseCase, UpdatePartyAddressUseCase, GetPartyAddressUseCase,
    DeletePartyAddressUseCase, ListPartyAddressUseCase,
};
pub use party_contact_usecases::{
    CreatePartyContactUseCase, UpdatePartyContactUseCase, GetPartyContactUseCase,
    DeletePartyContactUseCase, ListPartyContactUseCase,
};
pub use party_email_usecases::{
    CreatePartyEmailUseCase, UpdatePartyEmailUseCase, GetPartyEmailUseCase,
    DeletePartyEmailUseCase, ListPartyEmailUseCase,
};
pub use party_phone_usecases::{
    CreatePartyPhoneUseCase, UpdatePartyPhoneUseCase, GetPartyPhoneUseCase,
    DeletePartyPhoneUseCase, ListPartyPhoneUseCase,
};

// <<< CUSTOM
// END CUSTOM
