//! Use case type aliases for PartyEmail aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreatePartyEmailDto, UpdatePartyEmailDto};
use crate::application::service::PartyEmailService;
use crate::domain::entity::PartyEmail;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreatePartyEmailUseCase = CreateUseCase<PartyEmail, CreatePartyEmailDto, PartyEmailService>;
pub type UpdatePartyEmailUseCase = UpdateUseCase<PartyEmail, UpdatePartyEmailDto, PartyEmailService>;
pub type GetPartyEmailUseCase    = GetUseCase<PartyEmail, PartyEmailService>;
pub type DeletePartyEmailUseCase = DeleteUseCase<PartyEmail, PartyEmailService>;
pub type ListPartyEmailUseCase   = ListUseCase<PartyEmail, PartyEmailService>;

// <<< CUSTOM
// END CUSTOM
