//! Use case type aliases for PartyContact aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreatePartyContactDto, UpdatePartyContactDto};
use crate::application::service::PartyContactService;
use crate::domain::entity::PartyContact;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreatePartyContactUseCase = CreateUseCase<PartyContact, CreatePartyContactDto, PartyContactService>;
pub type UpdatePartyContactUseCase = UpdateUseCase<PartyContact, UpdatePartyContactDto, PartyContactService>;
pub type GetPartyContactUseCase    = GetUseCase<PartyContact, PartyContactService>;
pub type DeletePartyContactUseCase = DeleteUseCase<PartyContact, PartyContactService>;
pub type ListPartyContactUseCase   = ListUseCase<PartyContact, PartyContactService>;

// <<< CUSTOM
// END CUSTOM
