//! Use case type aliases for PartyPhone aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreatePartyPhoneDto, UpdatePartyPhoneDto};
use crate::application::service::PartyPhoneService;
use crate::domain::entity::PartyPhone;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreatePartyPhoneUseCase = CreateUseCase<PartyPhone, CreatePartyPhoneDto, PartyPhoneService>;
pub type UpdatePartyPhoneUseCase = UpdateUseCase<PartyPhone, UpdatePartyPhoneDto, PartyPhoneService>;
pub type GetPartyPhoneUseCase    = GetUseCase<PartyPhone, PartyPhoneService>;
pub type DeletePartyPhoneUseCase = DeleteUseCase<PartyPhone, PartyPhoneService>;
pub type ListPartyPhoneUseCase   = ListUseCase<PartyPhone, PartyPhoneService>;

// <<< CUSTOM
// END CUSTOM
