//! Use case type aliases for Party aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreatePartyDto, UpdatePartyDto};
use crate::application::service::PartyService;
use crate::domain::entity::Party;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreatePartyUseCase = CreateUseCase<Party, CreatePartyDto, PartyService>;
pub type UpdatePartyUseCase = UpdateUseCase<Party, UpdatePartyDto, PartyService>;
pub type GetPartyUseCase    = GetUseCase<Party, PartyService>;
pub type DeletePartyUseCase = DeleteUseCase<Party, PartyService>;
pub type ListPartyUseCase   = ListUseCase<Party, PartyService>;

// <<< CUSTOM
// END CUSTOM
