//! Use case type aliases for PartyAddress aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreatePartyAddressDto, UpdatePartyAddressDto};
use crate::application::service::PartyAddressService;
use crate::domain::entity::PartyAddress;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreatePartyAddressUseCase = CreateUseCase<PartyAddress, CreatePartyAddressDto, PartyAddressService>;
pub type UpdatePartyAddressUseCase = UpdateUseCase<PartyAddress, UpdatePartyAddressDto, PartyAddressService>;
pub type GetPartyAddressUseCase    = GetUseCase<PartyAddress, PartyAddressService>;
pub type DeletePartyAddressUseCase = DeleteUseCase<PartyAddress, PartyAddressService>;
pub type ListPartyAddressUseCase   = ListUseCase<PartyAddress, PartyAddressService>;

// <<< CUSTOM
// END CUSTOM
