//! HTTP handlers
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod party_handler;
pub mod party_address_handler;
pub mod party_contact_handler;
pub mod party_email_handler;
pub mod party_phone_handler;

// <<< CUSTOM
pub mod guarded_routes;
// END CUSTOM

// Re-exports
pub use party_handler::{create_party_routes, create_party_read_routes, create_party_write_routes};
pub use party_address_handler::{create_party_address_routes, create_party_address_read_routes, create_party_address_write_routes};
pub use party_contact_handler::{create_party_contact_routes, create_party_contact_read_routes, create_party_contact_write_routes};
pub use party_email_handler::{create_party_email_routes, create_party_email_read_routes, create_party_email_write_routes};
pub use party_phone_handler::{create_party_phone_routes, create_party_phone_read_routes, create_party_phone_write_routes};
// <<< CUSTOM
pub use guarded_routes::create_guarded_party_routes;
// END CUSTOM